:PROPERTIES:
:ID:       4cadd76b-bcf2-4e35-8205-41c606109a13
:END:

#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_VERSION: 4
#+OPTIONS: reveal_slide_number:t

#+title: CPP
filetags: CPP

* C++ Basics
:PROPERTIES:
:ID: C++ Basics
:END:
** Objects and Variables
:PROPERTIES:
:ID: Objects and Variables
:END:

In C++ direct memory access is discouraged. So we use objects for that.
Instead of telling go get the value stored in mailbox number 7532, we tell go get the value stored by this object.
So that the compiler can figure it out how to retrive the value

Variable

Memory is allocated during the run time.

#+begin_src cpp
#include <iostream>

int main() {

    int x;

    return 0;
}
#+end_src
*** Variable assigment
#+begin_src cpp
#include <iosteam>
using namespace std;
int main() {
    int x {5};
    cout << x;
    return 0;
}
#+end_src

#+RESULTS:
: 5

#+begin_src cpp
int a;         // default-initialization (no initializer)

// Traditional initialization forms:
int b = 5;     // copy-initialization (initial value after equals sign)
int c ( 6 );   // direct-initialization (initial value in parenthesis)

// Modern initialization forms (preferred):
int d { 7 };   // direct-list-initialization (initial value in braces)
int e {};      // value-initialization (empty braces)
#+end_src
*** maybe unused

#+begin_src cpp
#include <iostream>

int main()
{
    [[maybe_unused]] double pi { 3.14159 };  // Don't complain if pi is unused
    [[maybe_unused]] double gravity { 9.8 }; // Don't complain if gravity is unused
    [[maybe_unused]] double phi { 1.61803 }; // Don't complain if phi is unused

    std::cout << pi << '\n';
    std::cout << phi << '\n';

    // The compiler will no longer warn about gravity not being used

    return 0;
}
#+end_src
*** cout and cin
#+begin_src cpp
#include <iostream>
using namespace std;
int main() {
    int x{},y{};
    cin >> x >> y;
    cout << x << " " <<  y << '\n';
    return 0;
}
#+end_src

#+begin_src cpp
#include <iostream>
using namespace std;
int main() {
    int x{};
    cin >> x;

    int y{};
    cin >> y;

    cout << x << " " << y << "\n";
    return 0;
}

#+end_src

#+begin_src cpp
#include <iostream>  // for std::cout and std::cin

int main()
{
    std::cout << "Enter a number: "; // ask user for a number
    int x{}; // define variable x to hold user input
    std::cin >> x; // get number from keyboard and store it in variable x
    std::cout << "You entered " << x << '\n';

    return 0;
}
#+end_src
*** Uninitialized variables and undefined behavioure

Returns garbage value ----> Memory address

#+begin_src cpp
#include <iostream>

int main() {
    int x;
    std::cout << x << '\n';
    return 0;
}

#+end_src

#+RESULTS:
: 32765
*** Keywords and Identifiers

List of 92 keywords

| Keyword   | Keyword      | Keyword          | Keyword       |
|-----------+--------------+------------------+---------------|
| alignas   | const_cast   | int              | static_assert |
| alignof   | continue     | long             | static_cast   |
| and       | co_await     | mutable          | struct        |
| and_eq    | co_return    | namespace        | switch        |
| asm       | co_yield     | new              | template      |
| auto      | decltype     | noexcept         | this          |
| bitand    | default      | not              | thread_local  |
| bitor     | delete       | not_eq           | throw         |
| bool      | do           | nullptr          | true          |
| break     | double       | operator         | try           |
| case      | dynamic_cast | or               | typedef       |
| catch     | else         | or_eq            | typeid        |
| char      | enum         | private          | typename      |
| char8_t   | explicit     | protected        | union         |
| char16_t  | export       | public           | unsigned      |
| char32_t  | extern       | register         | using         |
| class     | false        | reinterpret_cast | virtual       |
| compl     | float        | requires         | void          |
| concept   | for          | return           | volatile      |
| const     | friend       | short            | wchar_t       |
| consteval | goto         | signed           | while         |
| constexpr | if           | sizeof           | xor           |
| constinit | fnline       | static           | xor_eq        |
** Functions and Files
:PROPERTIES:
:ID: Functions and Files
:END:

#+begin_src cpp
#include <iostream>

int returnvalue()
{
    int a;
    std::cin >> a;
    return a;
}

int main()
{
    int num { returnvalue() };

    std::cout << num << '\n';

    return 0;
}
#+end_src
*** Void functions
#+begin_src cpp
#include <iostream>

void printHi()
{
    std::cout << "Hi" << '\n';
}

int main() {

    //printHi();
    std::cout << printHi() << '\n';
    return 0;
}
#+end_src


#+begin_src cpp
#include <iostream>

int main() {

    unsigned short a{0};
    std::cout << a << '\n';

    a = -4;
    std::cout << a << '\n';

    return 0;
}
#+end_src

#+RESULTS:
** size_t[[https://www.learncpp.com/cpp-tutorial/fixed-width-integers-and-size-t/][ link to topic]]
:PROPERTIES:
:ID:       2713ca30-66c4-4558-9c6d-fedb727f44dd
:END:
** Char(ASCII TABLE LINK) [[https://www.learncpp.com/cpp-tutorial/chars/][here]]
:PROPERTIES:
:ID:       1cd7f4f7-4b72-4216-8122-afc737007b5a
:END:

#+begin_src cpp
#include <iostream>

int main() {
    char grade{65};
    std::cout << grade << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: A

#+begin_src cpp
#include <iostream> //

int main() {

    char grade {};

    std::cin >> grade;

    std::cout << grade << '\n';

    return 0;
}
#+end_src
** Implicit and Explicit Coversion
:PROPERTIES:
:ID: Implicit and Explicit Coversion
:END:

Implicit conversion are made by compilers whereas explicit are made manually

Syntax for Exclipit conversion ----> static_cast<new_type>(expression)

#+begin_src cpp :results output
#include <iostream>

int main() {

    double a{65.5};

    std::cout << a << '\n';

    std::cout << static_cast<int>(a) << '\n';

    std::cout << static_cast<char>(a) << '\n';

    std::cout << static_cast<float>(a) << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 65.5
: 65
: A
: 65.5
*** Sign conversion using static_cast
:PROPERTIES:
:ID:       Sign converstions using static_cast
:END:

#+begin_src cpp :results output
#include <iostream>

int main() {

    int x{-1};

    unsigned int y {static_cast<unsigned int>(x)};

    std::cout << y << '\n';

    unsigned int u {4294967295}; //here 4294967295 is largest 32bit unsigned int

    std::cout << static_cast<signed int>(u);

    return 0;
}
#+end_src

#+RESULTS:
: 4294967295
: -1

#+begin_src cpp
#include <iostream>

int main() {
    char a {};

    std::cin >> a;

    int b = a;

    std::cout << "You entered " << a << "," << "which has ACCII code " << b << '\n'; // OR use static_cast<int>(a) instead of another variable

    return 0;
}
#+end_src

#+RESULTS:
*** Quiz [[https://www.learncpp.com/cpp-tutorial/chapter-4-summary-and-quiz/][Questions]]

 Q2.
 #+begin_src cpp
#include <iostream>

int main() {
    double x,y;
    char c;
    std::cin >> x >> y;
    std::cout << "Enter +, -, *, /: " << '\n';
    std::cin >> c;

    if(c == '+') {
        std::cout << x+y << '\n';
    }else if (c == '-'){
        std::cout << x-y << '\n';

    }else if (c == '*'){
        std::cout << x*y << '\n';
    }else if (c == '/'){
        std::cout << x/y << '\n';
    }else {
        std::cout << "" << '\n';
    }


    return 0;
}
 #+end_src

Q3.
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    double height{};
    cout << "Enter the height of the tower in meters: ";
    cin >> height;

    double new_height{height};

    for(int i=0;new_height > 0;i++) {
        double distance_fallen = 9.8 * (i*i) /2.0;

       new_height = height - distance_fallen;

       if(new_height < 0) {
           cout << "At " << i << " seconds, " << "the ball is on the ground" << '\n';
           break;
       }
       cout << "At " << i << " seconds, " << "the ball is at height: " << new_height << " meters" << '\n';


    }

    return 0;
}
#+end_src
* Fundamental Data Types
:PROPERTIES:
:ID:       edec4bd0-e758-49cb-9d94-f3ddb493ddb6
:END:
** Numeral Systems (decimal, binary, hexadecimal)
:PROPERTIES:
:ID:       Numeral Systems (Decimal, hexadecimal..)
:END:
*** Octal

In octal there are no 8 and 9.
So 8 is represented as 10 and
9 - 11
10 - 12
15 - 17
16 - 20
17 - 21 and so on

For representing it as octal number we use "0" infront of the number

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{017};
    cout << x << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 15
*** hexadecimal

Hexadecimal base is 16 and we count like  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F, 10, 11, 12, …
To use hexadecimal we use prefix "0x"
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{0xF};
    int y{0x1A}; //here 1A in hexadecimal means 26 in decimal
    cout << x << '\n';
    cout << y << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 15
: 26
*** Binary

Binary has base 2.
We use prefix 0b for binary numbers
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{0101}; //octal
    int y{0x101}; //hexadecimal
    int z{0b101}; //binary

    cout << x << '\n';
    cout << y << '\n';
    cout << z << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 65
: 257
: 5
*** Outputting values in decimal, octal and hexadecimal

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{44};

    cout << hex << x << '\n';
    cout << oct << x << '\n';
    cout << dec << x << '\n';
    cout <<  x << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: 2c
: 54
: 44
: 44
*** Outputting values in Binary using std::bitset

#+begin_src cpp :results output
#include <iostream>
#include <bitset>

using namespace std;

int main() {
    bitset<4> x {5};
    bitset<8> y {20};
    bitset<8> z {0xF}; //decimal 15

    cout << x << '\n';
    cout << y << '\n';
    cout << z << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 0101
: 00010100
: 00001111
* Strings
:PROPERTIES:
:ID:       f325424f-36cb-44cc-8ab1-d062e4292603
:END:
** Strings (std::string)
:PROPERTIES:
:ID:       Strings (std::string)
:END:

The header <string> helps to input and output strings of different size

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    string name {"Shiva"};
    cout << name << '\n';

    name = "Prasad37";
    cout << name << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: Shiva
: Prasad37
** Strings (std::string_view)
:PROPERTIES:
:ID: Strings (std::string_view)
:END:
- string_view is used for reading a string in a more cleaner way.
- Instead of creating a copy of string again where required like std::string.
- It just points to the original data.

- For modifies and chaning the original string value ---- std::string
- For viewing the data in the string ---- std::string_view

For using string_view we have to use <string_view> header file

#+begin_src cpp :results output
#include <iostream>
#include <string>
#include <string_view>
using namespace std;

void string_View(string_view x) {  // here no copy is made it just points to original data
    cout << x << '\n';

    //string z {"Kyaram"};    Doesnt work here
    //x += z;
    //cout << x << '\n';
}

void String(string y) {  //here it creates the copy so we can modify the contents here
    cout << y << '\n';

    string z {"Kyaram"};
    y += z;
    cout << y << '\n';
}

int main() {
    string name {"Shivaprasad"};

    string_View(name);

    String(name);

    return 0;
}
#+end_src

Example

#+begin_src cpp :results output
#include <iostream>
#include <string>
#include <string_view>
using namespace std;

int main() {

    string name {"Shiva"};
    string_view name1 {name};

    cout << name1 << '\n';

    name1 = "Kyaram";
    cout << name1 << '\n';

    cout << name << '\n';

    return 0;
}
#+end_src
* Operators
:PROPERTIES:
:ID: Operators
:END:
[[https://www.learncpp.com/cpp-tutorial/operator-precedence-and-associativity/][Operator Precedence table]]

Exponent

#+begin_src cpp :results output
#include <iostream>
#include <cmath>

int main() {
    int x{2};
    std::cout << std::pow(x,2) << '\n';
    return 0;
}
#+end_src
* Bit Manipulation
:PROPERTIES:
:ID:       8c53eb59-116d-4f75-9345-128c4a166dcb
:END:
** Uses of <bitset> library
:PROPERTIES:
:ID: <Uses of <bitset> library>
:END:
It has
1. test()
2. set()
3. reset()
4. flip()

#+begin_src cpp :results output
#include <iostream>
#include <bitset>
using namespace std;

int main() {
    bitset<8> bits{0b0000'0101};

    cout << bits << '\n';
    cout << bits.test(2) << '\n';
    bits.set(1);
    cout << bits << '\n';
    bits.reset(0);
    cout << bits << '\n';
    bits.flip(0);
    cout << bits << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: 00000101
: 1
: 00000111
: 00000110
: 00000111

[[https://www.learncpp.com/cpp-tutorial/bitwise-operators/][Quiz]]

#+begin_src cpp :results output
#include <bitset>
#include <iostream>

// "rotl" stands for "rotate left"
std::bitset<4> rotl(std::bitset<4> bits)
{
    if(bits.test(3) == 0) {
        bits <<= 1;
    }else {
       bits <<= 1;
       bits.set(0);
    }

    return bits;
}

int main()
{
    std::bitset<4> bits1{ 0b0001 };
    std::cout << rotl(bits1) << '\n';

    std::bitset<4> bits2{ 0b0101 };
    std::cout << rotl(bits2) << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: 0010
: 1010

#+begin_src cpp :results output
#include <bitset>
#include <iostream>

std::bitset<4> rotl(std::bitset<4> bits)
{
    return (bits<<1) | (bits>>3);
}

int main()
{
    std::bitset<4> bits1{ 0b0001 };
    std::cout << rotl(bits1) << '\n';

    std::bitset<4> bits2{ 0b1001 };
    std::cout << rotl(bits2) << '\n';

    return 0;
}
#+end_src
** Bitmanipulation by bit masks
:PROPERTIES:
:ID: Bitmanipulation by bit masks
:END:

Bit masks --- These are predefined set of bits used to select which specific will be modified

#+begin_src cpp :results output
#include <cstdint>

constexpr std::uint8_t mask0{ 0b0000'0001 }; // represents bit 0
constexpr std::uint8_t mask1{ 0b0000'0010 }; // represents bit 1
constexpr std::uint8_t mask2{ 0b0000'0100 }; // represents bit 2
constexpr std::uint8_t mask3{ 0b0000'1000 }; // represents bit 3
constexpr std::uint8_t mask4{ 0b0001'0000 }; // represents bit 4
constexpr std::uint8_t mask5{ 0b0010'0000 }; // represents bit 5
constexpr std::uint8_t mask6{ 0b0100'0000 }; // represents bit 6
constexpr std::uint8_t mask7{ 0b1000'0000 }; // represents bit 7
#+end_src


1. Checking if a bit is on or off by using bit masks - We use AND(&) operator.
2. To set a bit - we use OR equals(|=) operator
3. To reset a bit - We use bitwise AND and bitwise NOT operator (&= ~)
4. To flip a bit - we use bitwise XOR (^=) operator

#+begin_src cpp :results output
#include <iostream>
#include <cstdint>

int main() {
    constexpr std::uint8_t mask0{ 0b0000'0001 }; // represents bit 0
    constexpr std::uint8_t mask1{ 0b0000'0010 }; // represents bit 1
    constexpr std::uint8_t mask2{ 0b0000'0100 }; // represents bit 2
    constexpr std::uint8_t mask3{ 0b0000'1000 }; // represents bit 3
    constexpr std::uint8_t mask4{ 0b0001'0000 }; // represents bit 4
    constexpr std::uint8_t mask5{ 0b0010'0000 }; // represents bit 5
    constexpr std::uint8_t mask6{ 0b0100'0000 }; // represents bit 6
    constexpr std::uint8_t mask7{ 0b1000'0000 }; // represents bit 7

    std::uint8_t flags {0b0000'0101}; // It means bit 0 and 2 are ON.

    std::cout << (static_cast<bool>(flags & mask0)? "ON\n" : "OFF\n");  // TO CHECK ON AND OFF

    std::cout << (static_cast<bool>(flags & mask1)? "ON\n" : "OFF\n");

    flags |= mask1; // TO SET THE BIT
    flags |= (mask3 | mask4 | mask5); // TO SET MULTIPLE BITS
    std::cout << (static_cast<bool>(flags & mask1)? "ON\n" : "OFF\n");

    flags &= ~mask1; //TO RESET THE BIT
    std::cout << (static_cast<bool>(flags & mask1)? "ON\n" : "OFF\n");

    flags ^= mask1; //TO FLIP THE BIT
    std::cout << (static_cast<bool>(flags & mask1)? "ON\n" : "OFF\n");

    return 0;
}

#+end_src

#+RESULTS:
: ON
: OFF
: ON
: OFF
: ON

[[https://www.learncpp.com/cpp-tutorial/bit-manipulation-with-bitwise-operators-and-bit-masks/][Quiz]]

#+begin_src cpp :results output
#include <bitset>
#include <cstdint>
#include <iostream>

int main()
{
    [[maybe_unused]] constexpr std::uint8_t option_viewed{ 0x01 };
    [[maybe_unused]] constexpr std::uint8_t option_edited{ 0x02 };
    [[maybe_unused]] constexpr std::uint8_t option_favorited{ 0x04 };
    [[maybe_unused]] constexpr std::uint8_t option_shared{ 0x08 };
    [[maybe_unused]] constexpr std::uint8_t option_deleted{ 0x10 };

    std::uint8_t myArticleFlags{ option_favorited };
    std::cout << std::bitset<8>{ myArticleFlags } << '\n';

    myArticleFlags |= option_viewed;
    std::cout << (static_cast<bool>(option_favorited & option_deleted)? "NOT DELETED\n" : "DELETED\n");

    myArticleFlags &= ~option_favorited;
    std::cout << std::bitset<8>{ myArticleFlags } << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 00000100
: DELETED
: 00000001

Q1. Write a program that asks the user to input a number between 0 and 255. Print this number as an 8-bit binary number (of the form #### ####). Don’t use any bitwise operators. Don’t use std::bitset

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int decimal_num{};

    cout << "Enter a number between 0 and 255\n";
    cin >> decimal_num;

    for(int divisor{128}; divisor >= 1; divisor /= 2) {
        if((decimal_num/divisor)%2 == 0) {
            cout << '0';
        }else {
            cout << '1';
        }
    }

    return 0;
}
#+end_src
* Namespace and scope resolution
:PROPERTIES:
:ID: Namespace and scope resolution
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

namespace Foo
{
    int dosomething(int a, int b) {
        return a+b;
    }
}
namespace Goo
{
    int dosomething(int a, int b) {
        return a-b;
    }
}

int main()
{
    cout << Goo::dosomething(1,2) << '\n';  // "::" ------> called scope resolution operator
    cout << Foo::dosomething(1,2) << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: -1
: 3
** Static local variables
:PROPERTIES:
:ID: Static local variables
:END:

local varibales --- created at the start of block and destroyed at the end of block
static local varibales ----- created at the start of program and destroyed at the end of program.

example without static
#+begin_src cpp :results output
#include <iostream>
using namespace std;

void increment()
{
    int x{1};
    ++x;
    cout << x << "\n";
}

int main() {
    increment();
    increment();
    increment();
    return 0;
}
#+end_src

#+RESULTS:
: 2
: 2
: 2

example with static
#+begin_src cpp :results output
#include <iostream>
using namespace std;

void increment()
{
    static int x{1};
    x++;
    cout << x << "\n";
}
int main() {
   increment();
   increment();
   increment();
    return 0;
}
#+end_src

#+RESULTS:
: 2
: 3
: 4
* Control Flow
:PROPERTIES:
:ID:       34549f34-c05a-4e23-ae24-8bdeb948cd13
:END:
** Switch case
:PROPERTIES:
:ID: Switch case
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {

    int x{3};

    switch(x)
    {
    case 1:
        cout << "One" << "\n";
        break;
    case 2:
        cout << "Two" << "\n";
        break;
    default:
        cout << "Error" << "\n";
        break;
    }

    return 0;
}
#+end_src

#+RESULTS:
: Error
** goto statements
:PROPERTIES:
:ID: goto statements
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

    void printhello(bool is)
    {
        if(is)
        {
            goto end;
        }
        cout << "Hello" << "\n";
end:
     cout << "end" << "\n";
    }

int main() {
    printhello(true);
    //printhello(false);
    return 0;
}
#+end_src

#+RESULTS:
: end
** While loop
:PROPERTIES:
:ID: While Loop
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    char alp{65};

   while(alp <= 90)
   {
       cout << alp << "-" << static_cast<int>(alp) << "\n";
       alp++;
   }

    return 0;
}
#+end_src



#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{5};

    while(x > 0)
    {
        int i = x;
        while(i > 0)
        {
            cout << i << " ";
            i--;
        }
        cout << "\n";
        x--;
    }

    return 0;
}
#+end_src

#+RESULTS:
: 5 4 3 2 1
: 4 3 2 1
: 3 2 1
: 2 1
: 1


#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{1};

    while(x <= 5)
    {
        int y{5};

        while(y>=1){
           if(y <= x){
               cout << y << ' ';
           }else {
               cout << " ";
           }
           --y;
        }
        cout << "\n";
        ++x;
    }
    return 0;
}
#+end_src

#+RESULTS:
:     1
:    2 1
:   3 2 1
:  4 3 2 1
: 5 4 3 2 1

#+begin_src cpp :results output
#include <iostream>
using namespace std;

void fizzbuzz(int x)
{
    for(int i=1;i<=x;i++)
    {
        if(i%3==0 && i%5==0) {
            cout << "FizzBuzz" << "\n";
        }else if(i%5==0){
           cout << "Buzz" << "\n";
        }else if(i%3==0){
            cout << "Fizz" << "\n";
        }else if(i%7==0){
            cout << "pop" << "\n";
        }else{
            cout << i << "\n";
        }
    }
}

int main() {
    int y;
    cin >> y;
    fizzbuzz(y);

    return 0;
}
#+end_src
** Do While
** For Loop
** std::exit
:PROPERTIES:
:ID: std::exit
:END:

When main function is returned a special function std::exit() is called with return value from main.
+ It performs number of cleanup functions.
  1. Objects with static storage duration are destroyed.
  2. Then some other miscellaneous file cleanup is done if any files were used.
+ calling std::exit explicitly.
  std::exit() is called implicitly when main function is returned. But we can also explicitly call the function
  For that we have to use <cstdlib> library

  #+begin_src cpp :results output
#include <iostream>
#include <cstdlib>
using namespace std;

int main() {

    cout << "Before exit" << "\n";

    exit(0);

    cout << "after exit" << "\n"; //This statement is never exucuted

    return 0;
}
#+end_src

std::exit() doesnt clean up local variable.Means
1. closing database and networks.
2. deallocating memory

For this we have to call another cleanup function before std::exit.
For making this easier there is another fucntion called std::atexit
std::atexit is called automatically when std::exit is called -------------> std::atexit(cleanup)
here cleanup is a function.
* Mersenne Twister
:PROPERTIES:
:ID: Mersenne twister
:END:

#+begin_src cpp :results output
#include <iostream>
#include <random>

int main() {
    std::mt19937 mt{};

    for(int i=0;i<=10;i++)
    {
        std::cout << mt() << "\n";
    }
    return 0;
}
#+end_src

#+RESULTS:
#+begin_example
3499211612
581869302
3890346734
3586334585
545404204
4161255391
3922919429
949333985
2715962298
1323567403
418932835
#+end_example
* Function Templates
:PROPERTIES:
:ID:       c1cad433-f953-497d-bbeb-fdc708761b6d
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

template <typename T>

T add(T x,T y)
{
    return x+y;
}

int main() {
   cout <<  add<float>(1.2,2.5) << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 3.7

* Constexpr and Consteval Functions
:PROPERTIES:
:ID: constexpr and consteval functions
:END:

constexpr functions are initialized at the compile time.
They may or maybe not be initialized at the compile time. But consteval functions are always evaluated at the compile time.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

constexpr int add(int x,int y)
{
    return x+y;
}

int main() {
    constexpr int x {add(1,2)};
    cout << x << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 3

consteval functions have to evaluate at the compile time only or else it will through an error.
These functions are also called as immediate fucntions

#+begin_src cpp :flags -std=gnu++20  :results output
#include <iostream>
using namespace std;

consteval int add(int x,int y)
{
    return x+y;
}

int main() {

    constexpr int a{add(10,20)}; // This will evaluate
    cout << a << "\n";

    cout << add(10,20) << "\n"; // This will evaluate

    int b{20};
    cout << add(10,b); //This will not evaluate.
    return 0;
}
#+end_src
* Compound data types
:PROPERTIES:
:ID: Compound data types
:END:

#+begin_mindmap
   ╭─ Functions
   ├─ C-style arrays
   ├─ Pointer Types ┬─ Pointer to Object
   │                ╰─ pointer to function
   ├─ Pointer to member types ┬─ pointer to data member
   │                          ╰─ pointer to member function
«» ┼─ Reference types ┬─ L-value references
   │                  ╰─ R-value references
   ├─ Enumerated Types ┬─ Unscoped enumerations
   │                   ╰─ Scoped enumerations
   │              ╭─ Structs
   ╰─ Class Types ┼─ Classes
                  ╰─ Unions
#+end_mindmap

** L-value references
:PROPERTIES:
:ID:       d46624f3-8fc2-47a4-a8a4-2e9fc383bf7f
:END:
*** Non-const L value references
:PROPERTIES:
:ID:       3e48fd10-66f1-4f0c-88c0-fde9e796e724
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{2};
    int& y{x};
    cout << y << "\n";
    cout << x << "\n";

    x = 4;
    cout << y << "\n";
    cout << x << "\n";

    y = 5;
    cout << y << "\n";
    cout << x << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 2
: 2
: 4
: 4
: 5
: 5
*** Const L-value referencs
:PROPERTIES:
:ID:       673d6af3-7c66-4f0b-8f1d-4017bb8e2c10
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {

    const int x {2};
    const int& ref{x};

    cout << ref << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 2

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{2};
    const int& ref{x};

    cout << ref << "\n";
    cout << x << "\n";

    x = 3;      // Modified by variables.
    cout << ref << "\n";

    ref = 4;    // Cannot be modified by ref since it is const
    cout << ref << "\n";

    return 0;
}
#+end_src

#+RESULTS:

If we initialize lvalue const reference to rvalue.
Then a temporary object is created with rvalue and reference to const is bound to that temporary object.
Temporary objects are destroyed at the end of the statement.
But this creates a dangling ref so that compilers extend the lifetime of temporary objects to match the lifetime of ref.

Non-const lvalue references require an lvalue (an object with a persistent memory address) because they are designed to allow modification of the referenced object.  Rvalues (such as temporary objects or literals) do not have a persistent memory address and are immutable; binding a non-const reference to them would allow modifications to an object that is immediately destroyed or cannot be changed, leading to undefined behavior or logical errors.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    const int& ref{2};
    cout << ref << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 2

with diif data types.
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    char alp{'T'};

    const int& ref{alp};

    cout << ref << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 84

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    double x {5};
    const int& ref{x};
    cout << ref << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 5
** Pass by reference
:PROPERTIES:
:ID: Pass by reference
:END:

#+begin_src cpp :results output
#include <iostream>
#include <string>
using namespace std;

void printname(string x)
{
    cout << x << "\n" ;
}

int main() {

    string name {"Shiva"};

    printname(name);

    return 0;
}
#+end_src

#+RESULTS:
: Shiva

Although the above program works fine.It is inefficent to make a copy of a string and will be destroyed  after the function.
So we use pass by reference.

#+begin_src cpp :results output
#include <iostream>
#include <string>
using namespace std;

void printname(string& ref)  //here we ref to name instead of making a copy
{
    cout << ref << "\n";
    ref = "Shiva";
    cout << ref << "\n";
}

int main() {
    string name{"Prasad"};
    printname(name);

    return 0;
}
#+end_src

#+RESULTS:
: Prasad
: Shiva

#+begin_src cpp :results output
#include <iostream>
using namespace std;
void passbyvalue(int x)
{
    cout << &x << "\n";
}

void passbyreference(int& x)
{
    cout << &x << "\n";
}
int main() {
    int x{2};
    cout << &x << "\n";
    passbyvalue(x);
    passbyreference(x);
    return 0;
}
#+end_src

#+RESULTS:
: 0x7ffc696819a4
: 0x7ffc6968198c
: 0x7ffc696819a4

Here we can notice the address of passbyreference and original varible is same.

** pass by const lvalue reference
:PROPERTIES:
:ID: pass by const lvalue reference
:END:
Unlike non-const lvalue reference for which we can bind to modifiable lvalues.
pass by const lvalue reference can be bind to modifiable, non-modifiable lvalues and rvalues.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

void print(const int& ref)
{
    cout << ref << "\n";
}

int main() {

    int x{2};  // we can pass nonconst varibales (modifiable)
    print(x);

    const int y{3};  // we can pass const varibales (non-modifiable)
    print(y);

    print(4);  // we can pass literal

    return 0;
}
#+end_src

#+RESULTS:
: 2
: 3
: 4

** why prefer std::string_view to const std::string&
:PROPERTIES:
:ID: why prefer std::string_view to const std::string&
:END:

| Argument Type          | std::string_view parameter | const std::string& parameter                 |
|------------------------+----------------------------+----------------------------------------------|
| std::string            | Inexpensive conversion     | Inexpensive reference binding                |
| std::string_view       | Inexpensive copy           | Expensive explicit conversion to std::string |
| C-style string/literal | Inexpensive conversion     | Expensive conversion                         |

#+begin_src cpp :results output
#include <iostream>
#include <string>
#include <string_view>

void printSV(std::string_view sv)
{
    std::cout << sv << '\n';
}

void printS(const std::string& s)
{
    std::cout << s << '\n';
}

int main()
{
    std::string s{ "Hello, world" };
    std::string_view sv { s };

    // Pass to `std::string_view` parameter
    printSV(s);              // ok: inexpensive conversion from std::string to std::string_view
    printSV(sv);             // ok: inexpensive copy of std::string_view
    printSV("Hello, world"); // ok: inexpensive conversion of C-style string literal to std::string_view

    // pass to `const std::string&` parameter
    printS(s);              // ok: inexpensive bind to std::string argument
    printS(sv);             // compile error: cannot implicit convert std::string_view to std::string
    printS(static_cast<std::string>(sv)); // bad: expensive creation of std::string temporary
    printS("Hello, world"); // bad: expensive creation of std::string temporary

    return 0;
}
#+end_src

** Pointers
:PROPERTIES:
:ID:       6c8fabe5-ab23-4a14-85da-a530791a14f5
:END:
*** Deference operator
:PROPERTIES:
:ID: Deference operator
:END:
& is address-of operator which returns address of object.
While * is used to return value at a given memory address as an lvalue.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{1};

    cout << x << "\n";
    cout << &x << "\n";  // gives address
    cout << *(&x) << "\n";  // gives value at that address

    return 0;
}
#+end_src

#+RESULTS:
: 1
: 0x7fff38edddc4
: 1
*** Pointer
:PROPERTIES:
:ID: Pointer
:END:

A Pointer is an object that holds a memory address as its value. This allows us to store the address of some other objects to use later.

#+begin_src cpp :results output
int;  // a normal int
int&; // an lvalue reference to an int value

int*; // a pointer to an int value (holds the address of an integer value)
#+end_src

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{1};
    int* ptr{&x};
    cout << *ptr << "\n";
    *ptr = 2;
    cout << *ptr << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 1
: 2


| Pointers                                       | References                                   |
|------------------------------------------------+----------------------------------------------|
| It can change the varibale it is being pointed | It cannot be changed it is being refered to. |
| Pointers are objects                           | References are not objects.                  |
| Pointers can point to nothing                  | References must always bound to an object    |
| Pointers are not required to be initialized    | References must be initialized               |

- The size of the pointer is independent to it is being pointed, instead it depends on architecture of the computer.
- In a 32 bit computer 4 bytes are taken and in 64 bit computer 8 bytes are taken.

*** Address of operator returns a pointer
:PROPERTIES:
:ID: Address of operator returns a pointer
:END:
The address of operator doesnt returns address of its operand as literal, Instead it returns a pointer to the operand.

#+begin_src cpp :results output
#include <iostream>
#include <typeinfo>
using namespace std;

int main() {
    int x{1};

    cout << typeid(x).name() << "\n";
    cout << typeid(&x).name() << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: i
: Pi
*** null pointers as boolean values
:PROPERTIES:
:ID: null pointers as boolean values
:END:

- Null pointer is implicitly converted to boolean value false.
- Not Null pointer is implicitly converted to boolean value true.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int* ptr{};

    if(ptr) {
        cout << "Not Null" << "\n";
    }else {
        cout << "Null" << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: Null
*** pointer to const
:PROPERTIES:
:ID:       819dd8ff-8d93-490b-80ad-ba2fc8e45b09
:END:

1. If the object is const then the pointer should be const.
2. If the object is non-const, we can still point a const pointer to it but we cannot change the value of object by deferencing pointer.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {

    const int x{2};
    const int* ptr{&x};

    cout << *ptr << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 2

we also make pointer ifself const. i.e, it doesnt change the address it is holding.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{1};

    int* const ptr{&x};
    cout << *ptr << "\n";

    int y{2}
    ptr = &y; // Do not possible

    return 0;
}
#+end_src

Const pointer to a const value
With this we cannot change the address and the value.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{2};
    const int* const ptr{&x};

    cout << *ptr << "\n";

    int y{3};

    ,*ptr = 3; // Not possible
    ptr = &y
    return 0;
}
#+end_src

#+RESULTS:
*** pass by address
:PROPERTIES:
:ID:       5c717542-3df3-46cb-ba1f-efb5f1a0e718
:END:

#+begin_src cpp :results output
#include <iostream>
#include <string>

void printByValue(std::string val) // The function parameter is a copy of str
{
    std::cout << val << '\n'; // print the value via the copy
}

void printByReference(const std::string& ref) // The function parameter is a reference that binds to str
{
    std::cout << ref << '\n'; // print the value via the reference
}

void printByAddress(const std::string* ptr) // The function parameter is a pointer that holds the address of str
{
    std::cout << *ptr << '\n'; // print the value via the dereferenced pointer
}

int main()
{
    std::string str{ "Hello, world!" };

    printByValue(str); // pass str by value, makes a copy of str
    printByReference(str); // pass str by reference, does not make a copy of str
    printByAddress(&str); // pass str by address, does not make a copy of str

    return 0;
}
#+end_src
** Operator overloading
:PROPERTIES:
:ID:       91f9c503-f53a-4d51-a398-10c9fe7be9dc
:END:

Operator overloading = writing your own function that runs when someone uses +, ==, <<, etc. on your custom data type.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Point {
    int x;
    int y;
};

Point operator+(Point a, Point b) {
    Point result;
    result.x = a.x + b.x;
    result.y = a.y + b.y;

    return result;
}

int main() {
    Point P1{1,2};
    Point P2{4,5};
    Point P3;
    P3 = P1 + P2;
    cout << P3.y;
    return 0;
}
#+end_src

#+RESULTS:
: 7


#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Point {
    int x;
    int y;
};

bool operator==(Point a, Point b) {
   return (a.x == b.x) && (a.y == b.y);
}

int main() {
    Point p1{1,2};
    Point p2{1,2};
    if(p1 == p2)
        cout << "Equal" << "\n";
    else
        cout << "Not equal" << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: Equal

#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Point {
    int x; int y;
};

ostream& operator+(ostream& hi, Point& p) {
    hi << "X: " << p.x << " Y: " << p.y;
    return hi;
}

int main() {
    Point P1{1,2};
    cout + P1;
    return 0;
}
#+end_src

#+RESULTS:
: X: 1 Y: 2

** Enumerations
:PROPERTIES:
:ID:       596bd0f2-f28c-40bb-9ec0-8de3600fc987
:END:
Enumerations are implicitly constexpr.
*** Unscoped Enumerations
:PROPERTIES:
:ID: Unscoped Enumerations
:END:
Each enumeration is numbered from 0. We can explicitly number a enumeration, any undefined enumeration will be given one value greater than the previous one.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

enum Color {red,white, yellow};

int main() {
    Color car{white};
    cout << car << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 1

#+begin_src cpp :results output
#include <iostream>
using namespace std;

namespace nothing{
    enum Color {
        red,
        white,
        yellow,
    };
}

int main() {

    nothing::Color apple{nothing::red}; //apple will store integral value 0.

    cout << apple << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 0

#+begin_src cpp :results output
#include <iostream>
using namespace std;
enum color {
    red,
    white,
    yellow,
};

int main() {
    color apple{static_cast<color>(2)};
    cout << apple << "\n";
    Return 0;
}
#+end_src

#+RESULTS:
: 2

#+begin_src cpp :results output
#include <iostream>
#include <string_view>
using namespace std;

enum Color {red, white, yellow, blue};

constexpr string_view Print(Color ref)
{
    switch(ref) {
        case red: return "red";
        case white: return "white";
        case yellow: return "Yellow";
        default: return "Error";
    }
}

int main() {
    constexpr Color apple{yellow};
    cout << Print(apple) << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: Yellow

#+begin_src cpp :results output
#include <iostream>
#include <string_view>
using namespace std;

namespace nothing {
    enum Color {white, yellow, red};
};

constexpr string_view print(nothing::Color ref) {
    switch(ref){
        case white: return "white";
        case yellow: return "yellow";
        case red: return "red";
        default: return "Error";
    }
}


int main() {

    nothing::Color jersey{nothing::white};

    cout << print(jersey) << "\n";

    return 0;
}
#+end_src
*** scoped Enumerations
:PROPERTIES:
:ID: Scoped Enumerations
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

enum class Color {white, red, green};

int main() {
    Color color {Color::white};
    cout << color << "\n";
    return 0;
}
#+end_src

#+RESULTS:


#+begin_src cpp :results output
#include <iostream>
using namespace std;

enum class cartoon {doreman, shinchan, bheem};

int main() {

    using enum cartoon;

    cartoon fav{shinchan};

    return 0;
}
#+end_src
** Struct
:PROPERTIES:
:ID: struct
:END:

A struct is a program defined data type that allows us to bundle multiple variables together into a single type.

1. Defining a struct
#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Employee {
    int id;
    int age;
    double salary;
}

int main() {

    return 0;
}
#+end_src

By declaring the struct it cannot occupy any space. But by initialization the object does.

Variables inside a group are called members.

2. Initialing a object.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Employee {
    int id;
    int age;
    double salary;
}

int main() {
    Employee gachibowli{};  // Object as created with the three varibles.
    return 0;
}
#+end_src

3. To access a specific member we use member selecion operator (.).

#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Employee {
    int id;
    int age;
    double salary;
};

int main() {
    Employee gachibowli{};  // Object as created with the three varibles.

    gachibowli.id = 1;
    cout << gachibowli.id << "\n";

    gachibowli.age = 67;
    cout << gachibowli.age << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 1
: 67


#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Point {
    int x{};
    int y{};
};

struct triangle {
    Point a{};
    Point b{};
    Point c{};
};

int main() {

    Point a{2,3};
    Point b{3,4};
    Point c{4,5};

    triangle tri{a,b,c};

    triangle* ptr(&tri);

    cout << (ptr -> c).x << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 4
** Classes (OOP)
:PROPERTIES:
:ID:       cd2cfe93-4c05-43da-aced-0b891ab966dd
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Date {
public:
    int m_day{};
    int m_month{};
    int m_year{};
};

void printdate(Date& date)
{
    cout << date.m_day << "/" << date.m_month << "/" << date.m_year << "\n";
}
int main() {
    Date date{19, 06, 2026};
    printdate(date);
    return 0;
}
#+end_src

*** member functions
:PROPERTIES:
:ID: member function
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Date {
public:
    int m_day{};
    int m_month{};
    int m_year{};

    void print() {
        cout << m_day << "/" << m_month << "/" << m_year << "\n";
    }
};

int main() {
    Date date{19, 06, 2026};

    date.print();
    return 0;
}
#+end_src

#+RESULTS:
: 19/6/2026

- member function with const object

  if the object is const then the member fucntion should also have to be a member fucntion.

#+begin_src cpp :results output
#include <iostream>
using namespace std;
class Car
{
public:
    int model{};
    int color_code{};

    void print() const {
       cout << "Model: " << model << " Color Code: " << color_code << "\n";
    }
};
int main() {

    const Car swift{1,79879};

    swift.print();

    return 0;
}
#+end_src

#+RESULTS:
: Model: 1 Color Code: 79879
\j*** access functions
 #+begin_src cpp :results output
#include <iostream>
usjing namespace std;

class House {
    int m_house_no{21};
    int m_members{9};

public:
    void print() {
        cout << m_house_no << " " << m_members << "\n";
    }

    int gethouseno() const {return m_house_no;}
    void sethouseno(int houseno) {m_house_no = houseno;}

    int getmembers() const {return m_members;}
    void setmembers(int members) {m_members = members;}
};

int main() {

    House my_house{};

    my_house.print();

    my_house.sethouseno(44);
    my_house.setmembers(4);

    cout << my_house.gethouseno() << "\n";
    cout << my_house.getmembers() << "\n";

    return 0;
\}
#+end_src
*** returning data members by lvalue reference
:PROPERTIES:
:ID:       d4ed5775-4900-4c30-aec6-ca6815d371b8
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

class House {
    int m_houseno{12};
    int m_members{3};

public:
    void print() {
        cout << m_houseno << " " << m_members << "\n";
    }

    int& gethouseno() {return m_houseno;}
};

int main() {
    House myhouse{};
    cout <<  myhouse.gethouseno();
    return 0;
}
#+end_src

#+RESULTS:
: 12

#+begin_src cpp :results output
#include <iostream>
#include <string>
using namespace std;
class Bike{
    string m_name{};
public:

    void setname(string_view name) {m_name = name;}

    string getname_byvalue() {
        return m_name;
    }

    string& getname_byreference() {
        return m_name;
    }
};

int main() {
    Bike bmw{};
    cout << bmw.getname_byvalue() << "\n";
    bmw.setname("BMW");
    cout << bmw.getname_byreference() << "\n";
    return 0;
}
#+end_src
*** constructor
:PROPERTIES:
:ID:       7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Foo{
    int m_a;
    int m_b;

public:
    Foo(int a,int b) {
        this->m_a = a;
        this->m_b = b;
    }

    //Foo(int a,int b) : m_a {a}, m_b {b}; {}

    void print() {
        cout << m_a << " " << m_b << "\n";
    }
};

int main() {
    Foo f{3,9};
    f.print();
    return 0;
}
#+end_src

1. A constructor is a special member function invoked when an object of class is created. It shares same name as class and has no return type.
2. It is responsible for initializing data members and setting initial state.


Delegating constructors
Constructors are allowed to delegate (transfer responsibility for) initialization to another constructor from the same class type. This process is sometimes called constructor chaining and such constructors are called delegating constructors.

   #+begin_src cpp :results output
#include <iostream>
using namespace std;

class Employee{
    string m_name{};
    int m_id{};
public:
    Employee(string name) :Employee(name, 0) {}

    Employee(string name, int id) : m_name {name}, m_id {id} {}

    void print() {
        cout << m_name << " " << m_id << "\n";
    }
};

int main() {
    Employee e1{"shiva"};
    e1.print();

    Employee e2{"shiva",9};
    e2.print();
    return 0;
}
#+end_src

#+RESULTS:
: shiva 0
: shiva 9

Reducing construtor using default arguments
   #+begin_src cpp :results output
#include <iostream>
using namespace std;

class Employee{
    string m_name{};
    int m_id{};
public:
    Employee(string name, int id = 0) : m_name {name}, m_id {id} {}

    void print() {
        cout << m_name << " " << m_id << "\n";
    }
};

int main() {
    Employee e1{"shiva"};
    e1.print();

    Employee e2{"shiva",9};
    e2.print();
    return 0;
}
#+end_src

#+RESULTS:
: shiva 0
: shiva 9

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Ball {
    string m_color{"black"};
    double m_radius{10.0};
public:
    Ball() {
        print();
    }

    Ball(string color) : m_color {color} {
        print();
    }

    Ball(double radius) : m_radius {radius} {
        print();
    }

    Ball(string color, double radius) : m_color {color} , m_radius {radius} {
        print();
    }

    void print() {
        cout << "Ball(" << m_color << ", " << m_radius << ")" <<  "\n";
    }
};
int main() {
    Ball def{};
    Ball blue("blue");
    Ball twenty{20};
    Ball bluetwenty{"blue", 20};
    return 0;
}
#+end_src

#+RESULTS:
: Ball(black, 10)
: Ball(blue, 10)
: Ball(black, 20)
: Ball(blue, 20)

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Ball{
    string m_name{};
    double m_radius{};
public:
    Ball(double radius) : Ball{"black", radius} {}

    Ball(string name = "black",double radius = 10.0) : m_name {name} , m_radius {radius} {print();}

    void print() {
        cout << "Ball(" << m_name << ", " << m_radius << ")" <<  "\n";
    }
};

int main() {
    Ball def{};
    Ball blue("blue");
    Ball twenty{20};
    Ball bluetwenty{"blue", 20};
    return 0;
}
#+end_src

#+RESULTS:
: Ball(black, 10)
: Ball(blue, 10)
: Ball(black, 20)
: Ball(blue, 20)
*** temporary object
:PROPERTIES:
:ID:       db0d93d4-f8b4-421c-aa05-cd9097953cbd
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Point{
    int m_x{};
    int m_y{};

public:
    Point(int x, int y) : m_x {x} , m_y {y} {};

    int x() {return m_x;}
    int y() {return m_y;}
};

void print(Point p) {
    cout << p.x() << " " << p.y() << "\n";
}

int main() {
    Point p1{1,2};
    print(p1);
    print(Point {3,4}  );
    print({1,2});
    return 0;
}
#+end_src

#+RESULTS:
: 1 2
: 3 4
: 1 2

- callling a constructor in a function creates a temporary object
*** delegating [[id:7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c][constructor]]
:PROPERTIES:
:ID:       75ef050f-974c-4aee-aaef-fb6c29857536
:END:
To make one [[id:7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c][constructor]] delegate to another construtor simply call the constructor in member initialization list of another [[id:7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c][constructor]].

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Employee {
    string m_name{};
    int m_age{};
public:
    Employee(string name) : Employee(name, 0) {}

    Employee(string name, int age) : m_name {name} , m_age {age} {cout << m_name << " " << m_age << "\n";}
};

int main() {
    Employee e1{"Shiva"};
    Employee e2{"PRASAD",2};
    return 0;
}
#+end_src

#+RESULTS:
: Shiva 0
: PRASAD 2
*** copy [[id:7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c][constructor]]
:PROPERTIES:
:ID:       6f470fe6-37ac-4cc1-97aa-bb5d0fdd4e90
:END:

A copy construtor is a construtor that is used to initialize an object using an existing object.

A copy [[id:7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c][constructor]] is implicitly created by compiler when we create a object using another object like in below. Although we can create copy [[id:7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c][constructor]] manually.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Number {
    int m_a{};
    int m_b{};
public:
    Number(int a, int b) : m_a {a}, m_b{b} {}

    void print() {
        cout << m_a << " " << m_b << endl;
    }
};

int main() {
    Number x{3,5};
    Number y{x};
    x.print();
    y.print();
    return 0;
}
#+end_src

#+RESULTS:
: 3 5
: 3 5

initiallzing a copy construtor manually.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Number {
    int m_a{};
    int m_b{};
public:
    Number(int a, int b) : m_a {a}, m_b{b} {}

    Number(Number& num) : m_a {num.m_a} , m_b {num.m_b} {
        cout << "Copy constructor is called" << "\n";
    }

    void print() {
        cout << m_a << " " << m_b << endl;
    }
};

int main() {
    Number x{3,5};
    Number y{x}; // here copy construtor is called
    x.print();
    y.print();
    return 0;
}
#+end_src

#+RESULTS:
: Copy constructor is called
: 3 5
: 3 5

creating a default copy construtor using *default*

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Fraction {
    int m_a{};
    int m_b{};
public:
    Fraction(int a, int b) : m_a{a}, m_b {b} {}

    Fraction(const Fraction& fraction) = default;

    void print() {
        cout << m_a << " " << m_b << "\n";
    }
};

int main() {
    Fraction f{1,2};
    Fraction f1{f};
    f.print();
    f1.print();
    return 0;
}
#+end_src

#+RESULTS:
: 1 2
: 1 2

using = delete to prevent copies

#+begin_src cpp :results output
#include <iostream>

class Fraction
{
private:
    int m_numerator{ 0 };
    int m_denominator{ 1 };

public:
    // Default constructor
    Fraction(int numerator=0, int denominator=1)
        : m_numerator{numerator}, m_denominator{denominator}
    {
    }

    // Delete the copy constructor so no copies can be made
    Fraction(const Fraction& fraction) = delete;

    void print() const
    {
        std::cout << "Fraction(" << m_numerator << ", " << m_denominator << ")\n";
    }
};

int main()
{
    Fraction f { 5, 3 };
    Fraction fCopy { f }; // compile error: copy constructor has been deleted

    return 0;
}
#+end_src

*** pass by value and copy construtor
:PROPERTIES:
:ID:       5dbdde02-e9f6-425f-943b-82d9f409f40c
:END:

when we pass an object by value to a function if the argument and parameter are of same class type then implicitly copy construtort is called.

in the beow code when an object is passed as value to a function then explicitly created copy construtor is invoked.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Number {
    int m_a{};
    int m_b{};
public:
    Number(int a, int b) : m_a {a}, m_b{b} {}

    Number(Number& num)  : m_a {num.m_a} , m_b {num.m_b} {
       cout << "copy construtor is called" << "\n";
   }

    void print() {
        cout << m_a << " " <<  m_b << "\n";
    }
};

void fun(Number x) {
    x.print();
}

int main() {
    Number x{12,3};
    fun(x);
    return 0;
}
#+end_src

#+RESULTS:
: copy construtor is called
: 12 3
*** Copy elison
:PROPERTIES:
:ID:       cb683dcd-2755-4ed2-85a8-c1ea0626e6b2
:END:
Copy elision is a compiler optimization technique that allows the compiler to remove unnecessary copying of objects. In other words, in cases where the compiler would normally call a copy constructor, the compiler is free to rewrite the code to avoid the call to the copy constructor altogether. When the compiler optimizes away a call to the copy constructor, we say the constructor has been elided.

*** User defined conversions
:PROPERTIES:
:ID:       2919e6a9-86ae-4c40-a82f-8ad364b0849c
:END:

here even though we the function *gets* has parameter Numbers class type in arguments we gave int. So the compiler implicitly converts the types.
These type of functions are called *user defined functions*.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Numbers {
    int m_a{};
public:
    Numbers(int a) : m_a {a} {}

    void print() {
        cout << m_a << "\n";
    }

};

void gets(Numbers num) {
    num.print();
}

int main() {
    gets(2);
    return 0;
}
#+end_src

#+RESULTS:
: 2
*** constexpr member functions
:PROPERTIES:
:ID:       ed2b9127-74e0-4db5-9d00-2a70e8ae9217
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Numbers {
    int m_a{};
    int m_b{};

    constexpr void print() {
        cout << m_a << " " << m_b << "\n";
    }
};

int main() {
    Numbers num{1,2};
    num.print();

    constexpr num1{3,4};
    num1.print();

    return 0;
}
#+end_src

#+RESULTS:
: 1 2

This works for aggregate functions functions like *struct* but not for *class*

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Numbers {
    int m_a{};
    int m_b{};

public:
    Numbers(int a, int b) : m_a{ a } , m_b {b} {}

    constexpr void print() {
        cout << m_a << " " << m_b << "\n";
    }
};
int main() {
    constexpr Numbers num{21,2};
    num.print() ;
    return 0;
}
#+end_src

#+RESULTS:

here when object is created the construtor is called which is of type class Numbers which is not constexpr so it doesnt run at runtime.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Numbers {
    int m_a{};
    int m_b{};

public:
    constexpr Numbers(int a, int b) : m_a{ a } , m_b {b} {}

    constexpr void print() {
        cout << m_a << " " << m_b << "\n";
    }
};
int main() {
    constexpr Numbers num{21,2};
    num.print();
    return 0;
}
#+end_src

#+RESULTS:

😭


#+begin_src cpp :results output
#include <iostream>
using namespace std;

class so{
    int m_a{};
public:
    so(int a) : m_a {a} {}

    void print() {
        cout << m_a << "\n";
    }
};

int main() {
    so a{1};
    a.print();

    so* b{&a};
    b->print();
    return 0;
}
#+end_src

#+RESULTS:
: 1
: 1

*** the hidden this pointer
:PROPERTIES:
:ID:       0027b492-1478-49c8-8761-9b7a46f57973
:END:

Inside every member function the keyword this is a const pointer that holds the address of current of object.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class numbers{
    int m_a{};
public:
    numbers(int a) :m_a {a} {}

    void print() {
        cout << this->m_a<< "\n";
    }
};

int main() {
    numbers n{1};
    n.print(&n);
    return 0;
}
#+end_src

#+RESULTS:

in the above the code can work simply if we put *m_a* instead of *this->m_a*
but this proves that there is a pointer of type numbers which stores address of object. so by using this->m_a it can access the m_a member.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Simple{
   int m_a{};
public:
    void set_a(int a) {
        m_a = a;
    }

    int get_a() {
        return m_a;
    }
};

int main() {
    Simple x{};
    x.set_a(2);
    cout << x.get_a() << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 2

here the compiler rewrites *x.set_a(2)* as *Simple::set_a(&Simple, 2)* internally

then the set_a function also changes in the class as

*void set_a(int a) {m_a = a}* ----------->>  static void set_a(Simple* const this, int a) {this->m_a =a;}

1. When we call simple.set_a(2), the compiler actually calls Simple::set_a(&simple, 2) and simple is passed by address to the function
2. The function has hidden parameter named *this* which receives the address of simple.
3. member variables inside set_a() are prefixed with *this->* which points to simple. So when compiler evaluates this->m_a, its actually resolving to simple.m_a

- Each member function has single this pointer parameter that points to the implicit object.

  Explicitly referencing this

  #+begin_src cpp :results output
#include <iostream>
using namespace std;

struct something {
    int a{};

    void set_a(int a) {
        this->a = a;
    }

    int get_a() {
        return a;
    }
};

int main() {
    something a{};
    a.set_a(1);
    cout << a.get_a();
    return 0;
}
#+end_src

#+RESULTS:
: 1

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class something{
    int a{};
public:
    void get() {
        cout << *this << "\n";
    }
};

int main() {
    int a{1};
    int* ptr{&a};
    cout << *ptr << "\n";
    something s{};
    s.get();
    return 0;
}
#+end_src

#+RESULTS:
*** member function chaining using *this
:PROPERTIES:
:ID:       c6d769ca-d2a1-45fd-99c3-4db1f9010bcd
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Cal{
    int m_a{0};
public:
    void add(int a) {m_a += a;}
    void sub(int a) {m_a -= a;}
    void mul(int a) {m_a *= a;}

    int get() {
        return m_a;
    }
};

int main() {
    Cal cal{};
    cal.add(3);
    cal.sub(1);
    cal.mul(4);
    cout << cal.get();
    return 0;
}
#+end_src

#+RESULTS:
: 8

Here to add, sub, and mul we need to call three diffrent member fuuntions seperating but with member fucntion chaining we can do it in a single line.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Cal{
    int m_a{0};
public:
    Cal& add(int a) {
        m_a += a;
        return *this;
    }

    Cal& sub(int a) {
        m_a -= a;
        return *this;
    }

    Cal& mul(int a) {
        m_a *= a;
        return *this;
    }

    int get() {
        return m_a;
    }

    void reset() {
        ,*this = {};
    }
};

int main() {
    Cal a{};
    a.add(3).sub(1).mul(3);
    cout << a.get() << "\n";

    a.reset();

    cout << a.get();
    return 0;
}
#+end_src

#+RESULTS:
: 6
: 0

here first add(3) runs and adds value 3 to m_a then it returns reference of the Cal object so
a.add(3).sub(1).mul(3) ------> a.sub(1).mul(3)

- Here we can reset the value of members using a member fucntion reset by *this = {}
- it creates a temporary Cal using default values of members and assigns it to current object.
*** Destructor
:PROPERTIES:
:ID:       727d415a-b93b-4d78-b574-c737c4e976fb
:END:
- Destructor is used for cleaning
- It is called automatically when an object of a class is destroyed.
- It doesnt have any arguments.
- It doesnt have any return type.
- It has name name as class preceding with a tilde(~).
- Although we can call destructor explicitly it is called automatically almost every time.
- If we dont not declare a dedtructot the compiler will implicitly declare a destructor with empty body.

  #+begin_src cpp :results output
#include <iostream>
using namespace std;

class Simple{
    int m_id{};
public:
    Simple(int id)  : m_id {id} {}

    ~Simple() {
        cout << "Destructor" << m_id << "\n";
    }

};

int main() {
    Simple s1(1);
    {
        Simple s2(2);
    }//s2 dies here so destructor of s2 is called first.
    return 0;
}//s1 dies here.
#+end_src

#+RESULTS:
: Destructor2
: Destructor1
*** static member variables and functions
:PROPERTIES:
:ID:       2bb1cb78-ea45-49ed-b90a-ff2b263501ba
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Something{
    static int a;
};

int Something::a{1};

int main() {

    Something something1{};
    Something something2{};

    something1.a = 2;

    cout << something1.a << "\n";
    cout << something2.a << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 2
: 2

Here we can see eventhough we changed the value of a for *something1* it has also changed for *something2*

*Static members are not associated with class objects* - we know that when we create a object it occupies memory for it, but when it comes to static member variables it will be created at the start of the program and destroyed at the program so it is independent of class object.

*When can say that - static members are global variables that live inside the scope region of a class*

Because it is independent of object we can access it with class name and scope resolution operator. just like above

It is declared as forward declare and the static members are accessed independent of access control like *private* *protected*, because the forward definations are not considered a way to access.

If we include a header file which has class definations there wont be initialized.
We have to initialize using access specifier but we can initialize to a static member if is inline.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Something{
    static inline int a{1};
};

int main() {
    Something something{};
    cout << something.a;
    return 0;
}
#+end_src

#+RESULTS:
: 1

Consider this

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Something {
    static inline int m_a{1};

public:
    int get() {
        return m_a;
    }
};

int main() {
    Something s{};
    cout << s.get();
    return 0;
}
#+end_src

#+RESULTS:
: 1

even though this works for getting the value it need to create a object.
for this reason we use static member functions.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Something{
    static inline int m_a{1};
public:
    static int get() {
        return m_a;
    }
};

int main() {
    cout << Something::get();
    return 0;
}
#+end_src

#+RESULTS:
: 1

here we accessed a private data member using static member function without creating an object.

- static member functions do not have *this pointer.
*** friend non-member functions
:PROPERTIES:
:ID:       de60d992-7ba5-4cf8-99ba-5ef22151eba3
:END:

Friend function or member is used for access private or protected data of a class to another class or function.

*friend is a class or function (member or non-member) that has been granted full access to the private and protected members of another class.*

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Something{
    int m_a{};
public:
    Something(int a) : m_a {a} {}

    friend void print(const Something& something); //declaration of friend function
};


void print(const Something& something) {
    cout << something.m_a;
}

int main() {
    Something nothing{1};
    print(nothing);
    return 0;
}
#+end_src

#+RESULTS:
: 1

defining friend non-member inside a class

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Something{
    int m_a{};
public:
    Something(int a) : m_a {a} {}

    friend void print(const Something& something) {
        cout << something.m_a;
    }
};

int main() {
    Something nothing{1};
    print(nothing);
    return 0;
}
#+end_src
*** friend class and friend member function
:PROPERTIES:
:ID:       246e1d8a-20cb-44b9-8832-7fcf8c38e48f
:END:
 A friend Class is that can access private and protected member of another class.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Storage{
    int m_d{};
    int m_n{};
public:
    Storage(int d,int n) : m_d {d} , m_n {n} {}

    friend class Display;
};

class Display{
    bool first{};

public:
    Display(bool b) : first {b} {}

    void displaystorage(Storage& storage) {
        if(first) {
            cout << storage.m_d << " " << storage.m_n << "\n";
        }else {
            cout << storage.m_n<< " " << storage.m_d << "\n";
        }
    }
};

int main() {
    Storage storage{10,20};
    Display display{false};

    display.displaystorage(storage); //here we are acessing the members of class Storage from class display

    return 0;
}
#+end_src

friend member funtion - instead of making an entire class friend we can make a function from another class a friend.
this can be done like this

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Display {};

class Storage{
    int m_a{};
    int m_n{};

public:
    Storageaint a, int n) : m_a {a} , m_n{n} {}

    friend void Display::displaystorage(const Storage& storage);
};

class Display{
    bool is{};
public:

    Display(bool b) : b{is} {}

    void displaystorage(const Storage& storage) {
        if(is) {
            cout << m_a << " " << m_n << "\n";
        }else {
            cout << m_n << " " << m_a << "\n";
        }
    }
};

int main() {

    Storage storage{10,20};
    Display display{true};

    display.displaystorage();

    return 0;
}
#+end_src

This doesnt work because the compiler will throw an error the it hasnt seen full defination of class Display

Instead we can do something like this

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Storage;

class Display{
   bool is{};
public:
    Display(bool b) : is{b} {}
    void displaystorage(Storage& storage);  // This is the reason we farward declared class Storage.
};

class Storage{
    int m_n{};
    int m_a{};
public:
    Storage(int n, int a) : m_n{n} , m_a{a} {}

    friend void Display::displaystorage(Storage& storage);
};

void Display::displaystorage(Storage& storage) {
    if(is) {
        cout << storage.m_n << " " << storage.m_a << "\n";
    }else {
        cout << storage.m_a << " " << storage.m_n << "\n";
    }
}

int main() {
    Storage storage{10,20};
    Display display{false};
    display.displaystorage(storage);
    return 0;
}
#+end_src

#+RESULTS:
: 20 10

[[https://www.learncpp.com/cpp-tutorial/friend-classes-and-friend-member-functions/][Quiz]]

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Vector{
    double m_x{};
    double m_y{};
    double m_z{};
public:
    Vector(double x, double y, double z) : m_x{x}, m_y{y} , m_z{z} {}

    void print() {
        cout << "x: " << m_x << " y: " << m_y << " z: " << m_z << "\n";
    }

    friend class Point;
};

class Point{
    double m_x{};
    double m_y{};
    double m_z{};
public:
    Point(double x,double y,double z) :m_x {x}, m_y{y}, m_z{z} {}

    void print() {
        cout << "x: " << m_x << " y: " << m_y << " z: " << m_z << "\n";
    }

    void movebyvector(Point& point) {
        cout << point.m_x + m_x << " " << point.m_y + m_y << " " << point.m_z + m_z << "\n";
    }
};

int main() {
    Vector vector{1.2, 2.2, 3.4};
    Point point{2.3, 3.4, 4.9};
    point.movebyvector(point);
    return 0;
}
#+end_src

#+RESULTS:
: 4.6 6.8 9.8



* Dynamic arrays
** Introduction to std::vector

#+begin_src cpp :results output
#include <iostream>
#include <vector>

int main() {
    std::vector<int> empty{};
    std::vector<int> whole{0,1,2,3};

    std::cout << whole[2];
    return 0;
}
#+end_src

#+RESULTS:
: 02

Containers typically have a special constructor called a list constructor that allows us to construct an instance of the container using an initializer list. The list constructor does three things:

1. Ensures the container has enough storage to hold all the initialization values (if needed).
2. Sets the length of the container to the number of elements in the initializer list (if needed).
3. Initializes the elements to the values in the initializer list (in sequential order).

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    const vector<int> arr{1,2};
    cout << arr[1];
    return 0;
}
#+end_src

#+RESULTS:

length using size() member function.

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector arr{1,2,3};
    cout << arr.size() << "\n";
    cout << size(arr);
    return 0;
}
#+end_src

#+RESULTS:
: 3
: 3

Since size() member function supports only unsigned numbers when we assign the length to a variable using size() it may result in signed/unsigned conversion warnings

Instead we cast using static cast

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector arr{1,2};
    //int length {arr.size()}; gives warning
    int length (static_cast<int>(arr.size()));
    cout << length;
    return 0;
}
#+end_src

#+RESULTS:
: 2

using ssize for length
- Since ssize is non-member function and returns lenght as long signed int we also need to cast this.j

  #+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector arr{1,2,3};
    int length {std::ssize(arr)};
    cout << length << "\n";
    return 0;
}
#+end_src

pass by reference

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

void fun(const vector<int>& arr) {
    cout << arr[0];
}

int main() {
    vector arr{1,2,3,4};
    fun(arr);
    return 0;
}
#+end_src

#+RESULTS:
: 1

we have to mention type of data in function parameter
we can use template

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;
template <typename T>
void fun(const vector<T>& arr) {
    cout << arr[0] << "\n";
}

int main() {
    vector arr1{1,2,3};
    vector arr2{1.2, 3.2};
    fun(arr1);
    fun(arr2);
    return 0;
}
#+end_src

#+RESULTS:
: 1
: 1.2

*** passing a std::vector using generic template or abbreviated function template
we can also create a template that can accpet any type of object.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {

    return 0;
}
#+end_src
