:PROPERTIES:
:ID:       8667b78f-2dc6-44f2-a893-a3718a247bb2
:END:
#+title: CPP
filetags: CPP

* C++ Basics
** Objects and Variables
:PROPERTIES:
:ID: Objects and Variables
:END:

In C++ direct memory access is discouraged. So we use objects for that.
Instead of telling go get the value stored in mailbox number 7532, we tell go get the value stored by this object.
So that the compiler can figure it out how to retrive the value

Variable

Memory is allocated during the run time.

#+begin_src cpp
#include <iostream>

int main() {

    int x;

    return 0;
}
#+end_src

*** Variable assigment
#+begin_src cpp
#include <iostream>
using namespace std;
int main() {
    int x {5};
    cout << x;
    return 0;
}
#+end_src

#+RESULTS:
: 5

#+begin_src cpp
int a;

int b = 5;
int c ( 6 );

int d { 7 };
int e {};
#+end_src

*** maybe unused

#+begin_src cpp
#include <iostream>

int main()
{
    [[maybe_unused]] double pi { 3.14159 };  // Don't complain if pi is unused
    [[maybe_unused]] double gravity { 9.8 };
    [[maybe_unused]] double phi { 1.61803 };

    std::cout << pi << '\n';
    std::cout << phi << '\n';


    return 0;
}
#+end_src
*** cout and cin
#+begin_src cpp
#include <iostream>
using namespace std;
int main() {
    int x{},y{};
    cin >> x >> y;
    cout << x << " " <<  y << '\n';
    return 0;
}
#+end_src

#+begin_src cpp
#include <iostream>
using namespace std;
int main() {
    int x{};
    cin >> x;

    int y{};
    cin >> y;

    cout << x << " " << y << "\n";
    return 0;
}

#+end_src

#+begin_src cpp
#include <iostream>  // for std::cout and std::cin

int main()
{
    std::cout << "Enter a number: "; // ask user for a number
    int x{}; // define variable x to hold user input
    std::cin >> x; // get number from keyboard and store it in variable x
    std::cout << "You entered " << x << '\n';

    return 0;
}
#+end_src
*** Uninitialized variables and undefined behavioure

Returns garbage value ----> Memory address

#+begin_src cpp
#include <iostream>

int main() {
    int x;
    std::cout << x << '\n';
    return 0;
}

#+end_src

#+RESULTS:
: 32765
*** Keywords and Identifiers

List of 92 keywords

| Keyword   | Keyword      | Keyword          | Keyword       |
|-----------+--------------+------------------+---------------|
| alignas   | const_cast   | int              | static_assert |
| alignof   | continue     | long             | static_cast   |
| and       | co_await     | mutable          | struct        |
| and_eq    | co_return    | namespace        | switch        |
| asm       | co_yield     | new              | template      |
| auto      | decltype     | noexcept         | this          |
| bitand    | default      | not              | thread_local  |
| bitor     | delete       | not_eq           | throw         |
| bool      | do           | nullptr          | true          |
| break     | double       | operator         | try           |
| case      | dynamic_cast | or               | typedef       |
| catch     | else         | or_eq            | typeid        |
| char      | enum         | private          | typename      |
| char8_t   | explicit     | protected        | union         |
| char16_t  | export       | public           | unsigned      |
| char32_t  | extern       | register         | using         |
| class     | false        | reinterpret_cast | virtual       |
| compl     | float        | requires         | void          |
| concept   | for          | return           | volatile      |
| const     | friend       | short            | wchar_t       |
| consteval | goto         | signed           | while         |
| constexpr | if           | sizeof           | xor           |
| constinit | fnline       | static           | xor_eq        |

** Functions and Files
:PROPERTIES:
:ID: Functions and Files
:END:


#+begin_src cpp
#include <iostream>

int returnvalue()
{
    int a;
    std::cin >> a;
    return a;
}

int main()
{
    int num { returnvalue() };

    std::cout << num << '\n';

    return 0;
}
#+end_src

*** Void functions
#+begin_src cpp
#include <iostream>

void printHi()
{
    std::cout << "Hi" << '\n';
}

int main() {

    //printHi();
    std::cout << printHi() << '\n';
    printf()
        printf()printf(jsbcb)print()
    return 0;printf
}
#+end_src


#+begin_src cpp
#include <iostream>

int main() {

    unsigned short a{0};
    std::cout << a << '\n';

    a = -4;
    std::cout << a << '\n';

    return 0;
}
#+end_src

#+RESULTS:

** size_t[[https://www.learncpp.com/cpp-tutorial/fixed-width-integers-and-size-t/][ link to topic]]

#+begin_src cpp
#include <iostream>

int main(){
    bool a = true;
    bool b = false;

    std::cout << a << '\n';
    std::cout << b << '\n';
    return 0;
}
#+end_src

** Char(ASCII TABLE LINK) [[https://www.learncpp.com/cpp-tutorial/chars/][here]]

#+begin_src cpp
#include <iostream>

int main() {
    char grade{65};
    std::cout << grade << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: A

#+begin_src cpp
#include <iostream> //

int main() {

    char grade {};

    std::cin >> grade;

    std::cout << grade << '\n';

    return 0;
}
#+end_src

** Implicit and Explicit Coversion

:PROPERTIES:
:ID: Implicit and Explicit Coversion
:END:

Implicit conversion are made by compilers whereas explicit are made manually

Syntax for Exclipit conversion ----> static_cast<new_type>(expression)

#+begin_src cpp :results output
#include <iostream>

int main() {

    double a{65.5};

    std::cout << a << '\n';

    std::cout << static_cast<int>(a) << '\n';

    std::cout << static_cast<char>(a) << '\n';

    std::cout << static_cast<float>(a) << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 65.5
: 65
: A
: 65.5

*** Sign conversion using static_cast
:PROPERTIES:
:ID: Sign converstions using static_cast
:END:

#+begin_src cpp :results output
#include <iostream>

int main() {

    int x{-1};

    unsigned int y {static_cast<unsigned int>(x)};

    std::cout << y << '\n';

    unsigned int u {4294967295}; //here 4294967295 is largest 32bit unsigned int

    std::cout << static_cast<signed int>(u);

    return 0;
}
#+end_src

#+RESULTS:
: 4294967295
: -1

#+begin_src cpp
#include <iostream>

int main() {
    char a {};

    std::cin >> a;

    int b = a;

    std::cout << "You entered " << a << "," << "which has ACCII code " << b << '\n'; // OR use static_cast<int>(a) instead of another variable

    return 0;
}
#+end_src

#+RESULTS:
*** Quiz [[https://www.learncpp.com/cpp-tutorial/chapter-4-summary-and-quiz/][Questions]]

 Q2.
 #+begin_src cpp
#include <iostream>

int main() {
    double x,y;
    char c;
    std::cin >> x >> y;
    std::cout << "Enter +, -, *, /: " << '\n';
    std::cin >> c;

    if(c == '+') {
        std::cout << x+y << '\n';
    }else if (c == '-'){
        std::cout << x-y << '\n';

    }else if (c == '*'){
        std::cout << x*y << '\n';
    }else if (c == '/'){
        std::cout << x/y << '\n';
    }else {
        std::cout << "" << '\n';
    }


    return 0;
}
 #+end_src

Q3.
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    double height{};
    cout << "Enter the height of the tower in meters: ";
    cin >> height;

    double new_height{height};

    for(int i=0;new_height > 0;i++) {
        double distance_fallen = 9.8 * (i*i) /2.0;

       new_height = height - distance_fallen;

       if(new_height < 0) {
           cout << "At " << i << " seconds, " << "the ball is on the ground" << '\n';
           break;
       }
       cout << "At " << i << " seconds, " << "the ball is at height: " << new_height << " meters" << '\n';


    }

    return 0;
}
#+end_src

** Numeral Systems (decimal, binary, hexadecimal)
:PROPERTIES:
:ID: Numeral Systems (Decimal, hexadecimal..)
:END:

*** Octal

In octal there are no 8 and 9.
So 8 is represented as 10 and
9 - 11
10 - 12
15 - 17
16 - 20
17 - 21 and so on

For representing it as octal number we use "0" infront of the number

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{017};
    cout << x << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 15

*** hexadecimal
Hexadecimal base is 16 and we count like  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F, 10, 11, 12, …
To use hexadecimal we use prefix "0x"
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{0xF};
    int y{0x1A}; //here 1A in hexadecimal means 26 in decimal
    cout << x << '\n';
    cout << y << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 15
: 26
*** Binary
Binary has base 2.
We use prefix 0b for binary numbers
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{0101}; //octal
    int y{0x101}; //hexadecimal
    int z{0b101}; //binary

    cout << x << '\n';
    cout << y << '\n';
    cout << z << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 65
: 257
: 5
*** Outputting values in decimal, octal and hexadecimal
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{44};

    cout << hex << x << '\n';
    cout << oct << x << '\n';
    cout << dec << x << '\n';
    cout <<  x << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: 2c
: 54
: 44
: 44
*** Outputting values in Binary using std::bitset

#+begin_src cpp :results output
#include <iostream>
#include <bitset>

using namespace std;

int main() {
    bitset<4> x {5};
    bitset<8> y {20};
    bitset<8> z {0xF}; //decimal 15

    cout << x << '\n';
    cout << y << '\n';
    cout << z << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 0101
: 00010100
: 00001111
*** Strings (std::string)
:PROPERTIES:
:ID: Strings (std::string)
:END:

To use strings easily. The header <string> helps to input and output stings of different size

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    string name {"Shiva"};
    cout << name << '\n';

    name = "Prasad37";
    cout << name << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: Shiva
: Prasad37
