:PROPERTIES:
:ID:       4cadd76b-bcf2-4e35-8205-41c606109a13
:END:

#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_VERSION: 4
#+OPTIONS: reveal_slide_number:t

#+title: CPP
filetags: CPP

* C++ Basics
:PROPERTIES:
:ID: C++ Basics
:END:
** Objects and Variables
:PROPERTIES:
:ID: Objects and Variables
:END:

In C++ direct memory access is discouraged. So we use objects for that.
Instead of telling go get the value stored in mailbox number 7532, we tell go get the value stored by this object.
So that the compiler can figure it out how to retrive the value

Variable

Memory is allocated during the run time.

#+begin_src cpp
#include <iostream>

int main() {

    int x;

    return 0;
}
#+end_src
*** Variable assigment
#+begin_src cpp
#include <iosteam>
using namespace std;
int main() {
    int x {5};
    cout << x;
    return 0;
}
#+end_src

#+RESULTS:
: 5

#+begin_src cpp
int a;         // default-initialization (no initializer)

// Traditional initialization forms:
int b = 5;     // copy-initialization (initial value after equals sign)
int c ( 6 );   // direct-initialization (initial value in parenthesis)

// Modern initialization forms (preferred):
int d { 7 };   // direct-list-initialization (initial value in braces)
int e {};      // value-initialization (empty braces)
#+end_src
*** maybe unused

#+begin_src cpp
#include <iostream>

int main()
{
    [[maybe_unused]] double pi { 3.14159 };  // Don't complain if pi is unused
    [[maybe_unused]] double gravity { 9.8 }; // Don't complain if gravity is unused
    [[maybe_unused]] double phi { 1.61803 }; // Don't complain if phi is unused

    std::cout << pi << '\n';
    std::cout << phi << '\n';

    // The compiler will no longer warn about gravity not being used

    return 0;
}
#+end_src
*** cout and cin
#+begin_src cpp
#include <iostream>
using namespace std;
int main() {
    int x{},y{};
    cin >> x >> y;
    cout << x << " " <<  y << '\n';
    return 0;
}
#+end_src

#+begin_src cpp
#include <iostream>
using namespace std;
int main() {
    int x{};
    cin >> x;

    int y{};
    cin >> y;

    cout << x << " " << y << "\n";
    return 0;
}

#+end_src

#+begin_src cpp
#include <iostream>  // for std::cout and std::cin

int main()
{
    std::cout << "Enter a number: "; // ask user for a number
    int x{}; // define variable x to hold user input
    std::cin >> x; // get number from keyboard and store it in variable x
    std::cout << "You entered " << x << '\n';

    return 0;
}
#+end_src
*** Uninitialized variables and undefined behavioure

Returns garbage value ----> Memory address

#+begin_src cpp
#include <iostream>

int main() {
    int x;
    std::cout << x << '\n';
    return 0;
}

#+end_src

#+RESULTS:
: 32765
*** Keywords and Identifiers

List of 92 keywords

| Keyword   | Keyword      | Keyword          | Keyword       |
|-----------+--------------+------------------+---------------|
| alignas   | const_cast   | int              | static_assert |
| alignof   | continue     | long             | static_cast   |
| and       | co_await     | mutable          | struct        |
| and_eq    | co_return    | namespace        | switch        |
| asm       | co_yield     | new              | template      |
| auto      | decltype     | noexcept         | this          |
| bitand    | default      | not              | thread_local  |
| bitor     | delete       | not_eq           | throw         |
| bool      | do           | nullptr          | true          |
| break     | double       | operator         | try           |
| case      | dynamic_cast | or               | typedef       |
| catch     | else         | or_eq            | typeid        |
| char      | enum         | private          | typename      |
| char8_t   | explicit     | protected        | union         |
| char16_t  | export       | public           | unsigned      |
| char32_t  | extern       | register         | using         |
| class     | false        | reinterpret_cast | virtual       |
| compl     | float        | requires         | void          |
| concept   | for          | return           | volatile      |
| const     | friend       | short            | wchar_t       |
| consteval | goto         | signed           | while         |
| constexpr | if           | sizeof           | xor           |
| constinit | fnline       | static           | xor_eq        |
** Functions and Files
:PROPERTIES:
:ID: Functions and Files
:END:

#+begin_src cpp
#include <iostream>

int returnvalue()
{
    int a;
    std::cin >> a;
    return a;
}

int main()
{
    int num { returnvalue() };

    std::cout << num << '\n';

    return 0;
}
#+end_src
*** Void functions
#+begin_src cpp
#include <iostream>

void printHi()
{
    std::cout << "Hi" << '\n';
}

int main() {

    //printHi();
    std::cout << printHi() << '\n';
    return 0;
}
#+end_src


#+begin_src cpp
#include <iostream>

int main() {

    unsigned short a{0};
    std::cout << a << '\n';

    a = -4;
    std::cout << a << '\n';

    return 0;
}
#+end_src

#+RESULTS:
** size_t[[https://www.learncpp.com/cpp-tutorial/fixed-width-integers-and-size-t/][ link to topic]]
:PROPERTIES:
:ID:       2713ca30-66c4-4558-9c6d-fedb727f44dd
:END:
** Char(ASCII TABLE LINK) [[https://www.learncpp.com/cpp-tutorial/chars/][here]]
:PROPERTIES:
:ID:       1cd7f4f7-4b72-4216-8122-afc737007b5a
:END:

#+begin_src cpp
#include <iostream>

int main() {
    char grade{65};
    std::cout << grade << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: A

#+begin_src cpp
#include <iostream> //

int main() {

    char grade {};

    std::cin >> grade;

    std::cout << grade << '\n';

    return 0;
}
#+end_src
** Implicit and Explicit Coversion
:PROPERTIES:
:ID: Implicit and Explicit Coversion
:END:

Implicit conversion are made by compilers whereas explicit are made manually

Syntax for Exclipit conversion ----> static_cast<new_type>(expression)

#+begin_src cpp :results output
#include <iostream>

int main() {

    double a{65.5};

    std::cout << a << '\n';

    std::cout << static_cast<int>(a) << '\n';

    std::cout << static_cast<char>(a) << '\n';

    std::cout << static_cast<float>(a) << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 65.5
: 65
: A
: 65.5
*** Sign conversion using static_cast
:PROPERTIES:
:ID:       Sign converstions using static_cast
:END:

#+begin_src cpp :results output
#include <iostream>

int main() {

    int x{-1};

    unsigned int y {static_cast<unsigned int>(x)};

    std::cout << y << '\n';

    unsigned int u {4294967295}; //here 4294967295 is largest 32bit unsigned int

    std::cout << static_cast<signed int>(u);

    return 0;
}
#+end_src

#+RESULTS:
: 4294967295
: -1

#+begin_src cpp
#include <iostream>

int main() {
    char a {};

    std::cin >> a;

    int b = a;

    std::cout << "You entered " << a << "," << "which has ACCII code " << b << '\n'; // OR use static_cast<int>(a) instead of another variable

    return 0;
}
#+end_src

#+RESULTS:
*** Quiz [[https://www.learncpp.com/cpp-tutorial/chapter-4-summary-and-quiz/][Questions]]

 Q2.
 #+begin_src cpp
#include <iostream>

int main() {
    double x,y;
    char c;
    std::cin >> x >> y;
    std::cout << "Enter +, -, *, /: " << '\n';
    std::cin >> c;

    if(c == '+') {
        std::cout << x+y << '\n';
    }else if (c == '-'){
        std::cout << x-y << '\n';

    }else if (c == '*'){
        std::cout << x*y << '\n';
    }else if (c == '/'){
        std::cout << x/y << '\n';
    }else {
        std::cout << "" << '\n';
    }


    return 0;
}
 #+end_src

Q3.
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    double height{};
    cout << "Enter the height of the tower in meters: ";
    cin >> height;

    double new_height{height};

    for(int i=0;new_height > 0;i++) {
        double distance_fallen = 9.8 * (i*i) /2.0;

       new_height = height - distance_fallen;

       if(new_height < 0) {
           cout << "At " << i << " seconds, " << "the ball is on the ground" << '\n';
           break;
       }
       cout << "At " << i << " seconds, " << "the ball is at height: " << new_height << " meters" << '\n';


    }

    return 0;
}
#+end_src
* Fundamental Data Types
:PROPERTIES:
:ID:       edec4bd0-e758-49cb-9d94-f3ddb493ddb6
:END:
** Numeral Systems (decimal, binary, hexadecimal)
:PROPERTIES:
:ID:       Numeral Systems (Decimal, hexadecimal..)
:END:
*** Octal

In octal there are no 8 and 9.
So 8 is represented as 10 and
9 - 11
10 - 12
15 - 17
16 - 20
17 - 21 and so on

For representing it as octal number we use "0" infront of the number

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{017};
    cout << x << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 15
*** hexadecimal

Hexadecimal base is 16 and we count like  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F, 10, 11, 12, …
To use hexadecimal we use prefix "0x"
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{0xF};
    int y{0x1A}; //here 1A in hexadecimal means 26 in decimal
    cout << x << '\n';
    cout << y << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 15
: 26
*** Binary

Binary has base 2.
We use prefix 0b for binary numbers
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{0101}; //octal
    int y{0x101}; //hexadecimal
    int z{0b101}; //binary

    cout << x << '\n';
    cout << y << '\n';
    cout << z << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 65
: 257
: 5
*** Outputting values in decimal, octal and hexadecimal

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{44};

    cout << hex << x << '\n';
    cout << oct << x << '\n';
    cout << dec << x << '\n';
    cout <<  x << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: 2c
: 54
: 44
: 44
*** Outputting values in Binary using std::bitset

#+begin_src cpp :results output
#include <iostream>
#include <bitset>

using namespace std;

int main() {
    bitset<4> x {5};
    bitset<8> y {20};
    bitset<8> z {0xF}; //decimal 15

    cout << x << '\n';
    cout << y << '\n';
    cout << z << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 0101
: 00010100
: 00001111
* Strings
:PROPERTIES:
:ID:       f325424f-36cb-44cc-8ab1-d062e4292603
:END:
** Strings (std::string)
:PROPERTIES:
:ID:       Strings (std::string)
:END:

The header <string> helps to input and output strings of different size

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    string name {"Shiva"};
    cout << name << '\n';

    name = "Prasad37";
    cout << name << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: Shiva
: Prasad37
** Strings (std::string_view)
:PROPERTIES:
:ID: Strings (std::string_view)
:END:
- string_view is used for reading a string in a more cleaner way.
- Instead of creating a copy of string again where required like std::string.
- It just points to the original data.

- For modifies and chaning the original string value ---- std::string
- For viewing the data in the string ---- std::string_view

For using string_view we have to use <string_view> header file

#+begin_src cpp :results output
#include <iostream>
#include <string>
#include <string_view>
using namespace std;

void string_View(string_view x) {  // here no copy is made it just points to original data
    cout << x << '\n';

    //string z {"Kyaram"};    Doesnt work here
    //x += z;
    //cout << x << '\n';
}

void String(string y) {  //here it creates the copy so we can modify the contents here
    cout << y << '\n';

    string z {"Kyaram"};
    y += z;
    cout << y << '\n';
}

int main() {
    string name {"Shivaprasad"};

    string_View(name);

    String(name);

    return 0;
}
#+end_src

Example

#+begin_src cpp :results output
#include <iostream>
#include <string>
#include <string_view>
using namespace std;

int main() {

    string name {"Shiva"};
    string_view name1 {name};

    cout << name1 << '\n';

    name1 = "Kyaram";
    cout << name1 << '\n';

    cout << name << '\n';

    return 0;
}
#+end_src

** some functions
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    string name = "Shiva";
    cout << name.front();
    cout << name.back();

    const char* ptr = name.c_str();

    cout << *ptr << '\n';
    ptr++;
    cout << *ptr << '\n';

    name.reserve(100);
    cout << name.capacity()<< '\n';

    name.shrink_to_fit();
    cout << name.capacity() << '\n';

    name.resize(20); //pad with \0;
    name.resize(15, '!'); //pad with !
    name.resize(3); //trancate


    string s = "Hello";
    cout << s.substr(1,3)<<'\n';
    cout << s.substr(1) << '\n';

    string h = "Hello world";
    size_t pos = h.find_first_of("aeiou"); //any vowel
    size_t pos1 = h.find_first_not_of("aeiou"); //any vowel
    cout << pos << '\n';
    cout << pos1 << '\n';

    string str = "hello hello";
    size_t start = 0;
    while((pos = str.find("o",start)) != string::npos) {
        cout << pos << " ";
        start = pos +1;
    }
    cout << '\n';

    string hi = "Hello world!";
    hi.replace(7,4, "hehe");

    // auto start = hi.begin(); //same result
    // auto end = start + 5;
    cout << hi  << '\n';
    return 0;
}
#+end_src

#+RESULTS:
#+begin_example
SaS
h
100
15
ell
ello
1
0
4 10
Hello whehe!
#+end_example

* Operators
:PROPERTIES:
:ID: Operators
:END:
[[https://www.learncpp.com/cpp-tutorial/operator-precedence-and-associativity/][Operator Precedence table]]

Exponent

#+begin_src cpp :results output
#include <iostream>
#include <cmath>

int main() {
    int x{2};
    std::cout << std::pow(x,2) << '\n';
    return 0;
}
#+end_src
* Bit Manipulation
:PROPERTIES:
:ID:       8c53eb59-116d-4f75-9345-128c4a166dcb
:END:
** Uses of <bitset> library
:PROPERTIES:
:ID: <Uses of <bitset> library>
:END:
It has
1. test()
2. set()
3. reset()
4. flip()

#+begin_src cpp :results output
#include <iostream>
#include <bitset>
using namespace std;

int main() {
    bitset<8> bits{0b0000'0101};

    cout << bits << '\n';
    cout << bits.test(2) << '\n';
    bits.set(1);
    cout << bits << '\n';
    bits.reset(0);
    cout << bits << '\n';
    bits.flip(0);
    cout << bits << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: 00000101
: 1
: 00000111
: 00000110
: 00000111

[[https://www.learncpp.com/cpp-tutorial/bitwise-operators/][Quiz]]

#+begin_src cpp :results output
#include <bitset>
#include <iostream>

// "rotl" stands for "rotate left"
std::bitset<4> rotl(std::bitset<4> bits)
{
    if(bits.test(3) == 0) {
        bits <<= 1;
    }else {
       bits <<= 1;
       bits.set(0);
    }

    return bits;
}

int main()
{
    std::bitset<4> bits1{ 0b0001 };
    std::cout << rotl(bits1) << '\n';

    std::bitset<4> bits2{ 0b0101 };
    std::cout << rotl(bits2) << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: 0010
: 1010

#+begin_src cpp :results output
#include <bitset>
#include <iostream>

std::bitset<4> rotl(std::bitset<4> bits)
{
    return (bits<<1) | (bits>>3);
}

int main()
{
    std::bitset<4> bits1{ 0b0001 };
    std::cout << rotl(bits1) << '\n';

    std::bitset<4> bits2{ 0b1001 };
    std::cout << rotl(bits2) << '\n';

    return 0;
}
#+end_src
** Bitmanipulation by bit masks
:PROPERTIES:
:ID: Bitmanipulation by bit masks
:END:

Bit masks --- These are predefined set of bits used to select which specific will be modified

#+begin_src cpp :results output
#include <cstdint>

constexpr std::uint8_t mask0{ 0b0000'0001 }; // represents bit 0
constexpr std::uint8_t mask1{ 0b0000'0010 }; // represents bit 1
constexpr std::uint8_t mask2{ 0b0000'0100 }; // represents bit 2
constexpr std::uint8_t mask3{ 0b0000'1000 }; // represents bit 3
constexpr std::uint8_t mask4{ 0b0001'0000 }; // represents bit 4
constexpr std::uint8_t mask5{ 0b0010'0000 }; // represents bit 5
constexpr std::uint8_t mask6{ 0b0100'0000 }; // represents bit 6
constexpr std::uint8_t mask7{ 0b1000'0000 }; // represents bit 7
#+end_src


1. Checking if a bit is on or off by using bit masks - We use AND(&) operator.
2. To set a bit - we use OR equals(|=) operator
3. To reset a bit - We use bitwise AND and bitwise NOT operator (&= ~)
4. To flip a bit - we use bitwise XOR (^=) operator

#+begin_src cpp :results output
#include <iostream>
#include <cstdint>

int main() {
    constexpr std::uint8_t mask0{ 0b0000'0001 }; // represents bit 0
    constexpr std::uint8_t mask1{ 0b0000'0010 }; // represents bit 1
    constexpr std::uint8_t mask2{ 0b0000'0100 }; // represents bit 2
    constexpr std::uint8_t mask3{ 0b0000'1000 }; // represents bit 3
    constexpr std::uint8_t mask4{ 0b0001'0000 }; // represents bit 4
    constexpr std::uint8_t mask5{ 0b0010'0000 }; // represents bit 5
    constexpr std::uint8_t mask6{ 0b0100'0000 }; // represents bit 6
    constexpr std::uint8_t mask7{ 0b1000'0000 }; // represents bit 7

    std::uint8_t flags {0b0000'0101}; // It means bit 0 and 2 are ON.

    std::cout << (static_cast<bool>(flags & mask0)? "ON\n" : "OFF\n");  // TO CHECK ON AND OFF

    std::cout << (static_cast<bool>(flags & mask1)? "ON\n" : "OFF\n");

    flags |= mask1; // TO SET THE BIT
    flags |= (mask3 | mask4 | mask5); // TO SET MULTIPLE BITS
    std::cout << (static_cast<bool>(flags & mask1)? "ON\n" : "OFF\n");

    flags &= ~mask1; //TO RESET THE BIT
    std::cout << (static_cast<bool>(flags & mask1)? "ON\n" : "OFF\n");

    flags ^= mask1; //TO FLIP THE BIT
    std::cout << (static_cast<bool>(flags & mask1)? "ON\n" : "OFF\n");

    return 0;
}

#+end_src

#+RESULTS:
: ON
: OFF
: ON
: OFF
: ON

[[https://www.learncpp.com/cpp-tutorial/bit-manipulation-with-bitwise-operators-and-bit-masks/][Quiz]]

#+begin_src cpp :results output
#include <bitset>
#include <cstdint>
#include <iostream>

int main()
{
    [[maybe_unused]] constexpr std::uint8_t option_viewed{ 0x01 };
    [[maybe_unused]] constexpr std::uint8_t option_edited{ 0x02 };
    [[maybe_unused]] constexpr std::uint8_t option_favorited{ 0x04 };
    [[maybe_unused]] constexpr std::uint8_t option_shared{ 0x08 };
    [[maybe_unused]] constexpr std::uint8_t option_deleted{ 0x10 };

    std::uint8_t myArticleFlags{ option_favorited };
    std::cout << std::bitset<8>{ myArticleFlags } << '\n';

    myArticleFlags |= option_viewed;
    std::cout << (static_cast<bool>(option_favorited & option_deleted)? "NOT DELETED\n" : "DELETED\n");

    myArticleFlags &= ~option_favorited;
    std::cout << std::bitset<8>{ myArticleFlags } << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 00000100
: DELETED
: 00000001

Q1. Write a program that asks the user to input a number between 0 and 255. Print this number as an 8-bit binary number (of the form #### ####). Don’t use any bitwise operators. Don’t use std::bitset

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int decimal_num{};

    cout << "Enter a number between 0 and 255\n";
    cin >> decimal_num;

    for(int divisor{128}; divisor >= 1; divisor /= 2) {
        if((decimal_num/divisor)%2 == 0) {
            cout << '0';
        }else {
            cout << '1';
        }
    }

    return 0;
}
#+end_src
* Namespace and scope resolution
:PROPERTIES:
:ID: Namespace and scope resolution
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

namespace Foo
{
    int dosomething(int a, int b) {
        return a+b;
    }
}
namespace Goo
{
    int dosomething(int a, int b) {
        return a-b;
    }
}

int main()
{
    cout << Goo::dosomething(1,2) << '\n';  // "::" ------> called scope resolution operator
    cout << Foo::dosomething(1,2) << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: -1
: 3
** Static local variables
:PROPERTIES:
:ID: Static local variables
:END:

local varibales --- created at the start of block and destroyed at the end of block
static local varibales ----- created at the start of program and destroyed at the end of program.

example without static
#+begin_src cpp :results output
#include <iostream>
using namespace std;

void increment()
{
    int x{1};
    ++x;
    cout << x << "\n";
}

int main() {
    increment();
    increment();
    increment();
    return 0;
}
#+end_src

#+RESULTS:
: 2
: 2
: 2

example with static
#+begin_src cpp :results output
#include <iostream>
using namespace std;

void increment()
{
    static int x{1};
    x++;
    cout << x << "\n";
}
int main() {
   increment();
   increment();
   increment();
    return 0;
}
#+end_src

#+RESULTS:
: 2
: 3
: 4
* Control Flow
:PROPERTIES:
:ID:       34549f34-c05a-4e23-ae24-8bdeb948cd13
:END:
** Switch case
:PROPERTIES:
:ID: Switch case
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {

    int x{3};

    switch(x)
    {
    case 1:
        cout << "One" << "\n";
        break;
    case 2:
        cout << "Two" << "\n";
        break;
    default:
        cout << "Error" << "\n";
        break;
    }

    return 0;
}
#+end_src

#+RESULTS:
: Error
** goto statements
:PROPERTIES:
:ID: goto statements
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

    void printhello(bool is)
    {
        if(is)
        {
            goto end;
        }
        cout << "Hello" << "\n";
end:
     cout << "end" << "\n";
    }

int main() {
    printhello(true);
    //printhello(false);
    return 0;
}
#+end_src

#+RESULTS:
: end
** While loop
:PROPERTIES:
:ID: While Loop
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    char alp{65};

   while(alp <= 90)
   {
       cout << alp << "-" << static_cast<int>(alp) << "\n";
       alp++;
   }

    return 0;
}
#+end_src



#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{5};

    while(x > 0)
    {
        int i = x;
        while(i > 0)
        {
            cout << i << " ";
            i--;
        }
        cout << "\n";
        x--;
    }

    return 0;
}
#+end_src

#+RESULTS:
: 5 4 3 2 1
: 4 3 2 1
: 3 2 1
: 2 1
: 1


#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{1};

    while(x <= 5)
    {
        int y{5};

        while(y>=1){
           if(y <= x){
               cout << y << ' ';
           }else {
               cout << " ";
           }
           --y;
        }
        cout << "\n";
        ++x;
    }
    return 0;
}
#+end_src

#+RESULTS:
:     1
:    2 1
:   3 2 1
:  4 3 2 1
: 5 4 3 2 1

#+begin_src cpp :results output
#include <iostream>
using namespace std;

void fizzbuzz(int x)
{
    for(int i=1;i<=x;i++)
    {
        if(i%3==0 && i%5==0) {
            cout << "FizzBuzz" << "\n";
        }else if(i%5==0){
           cout << "Buzz" << "\n";
        }else if(i%3==0){
            cout << "Fizz" << "\n";
        }else if(i%7==0){
            cout << "pop" << "\n";
        }else{
            cout << i << "\n";
        }
    }
}

int main() {
    int y;
    cin >> y;
    fizzbuzz(y);

    return 0;
}
#+end_src
** Do While
** For Loop
** std::exit
:PROPERTIES:
:ID: std::exit
:END:

When main function is returned a special function std::exit() is called with return value from main.
+ It performs number of cleanup functions.
  1. Objects with static storage duration are destroyed.
  2. Then some other miscellaneous file cleanup is done if any files were used.
+ calling std::exit explicitly.
  std::exit() is called implicitly when main function is returned. But we can also explicitly call the function
  For that we have to use <cstdlib> library

  #+begin_src cpp :results output
#include <iostream>
#include <cstdlib>
using namespace std;

int main() {

    cout << "Before exit" << "\n";

    exit(0);

    cout << "after exit" << "\n"; //This statement is never exucuted

    return 0;
}
#+end_src

std::exit() doesnt clean up local variable.Means
1. closing database and networks.
2. deallocating memory

For this we have to call another cleanup function before std::exit.
For making this easier there is another fucntion called std::atexit
std::atexit is called automatically when std::exit is called -------------> std::atexit(cleanup)
here cleanup is a function.
* Mersenne Twister
:PROPERTIES:
:ID: Mersenne twister
:END:

#+begin_src cpp :results output
#include <iostream>
#include <random>

int main() {
    std::mt19937 mt{};

    for(int i=0;i<=10;i++)
    {
        std::cout << mt() << "\n";
    }
    return 0;
}
#+end_src
* Function Templates
:PROPERTIES:
:ID:       c1cad433-f953-497d-bbeb-fdc708761b6d
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

template <typename T>

T add(T x,T y)
{
    return x+y;
}

int main() {
   cout <<  add<float>(1.2,2.5) << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 3.7

* Constexpr and Consteval Functions
:PROPERTIES:
:ID: constexpr and consteval functions
:END:

constexpr functions are initialized at the compile time.
They may or maybe not be initialized at the compile time. But consteval functions are always evaluated at the compile time.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

constexpr int add(int x,int y)
{
    return x+y;
}

int main() {
    constexpr int x {add(1,2)};
    cout << x << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 3

consteval functions have to evaluate at the compile time only or else it will through an error.
These functions are also called as immediate fucntions

#+begin_src cpp :flags -std=gnu++20  :results output
#include <iostream>
using namespace std;

consteval int add(int x,int y)
{
    return x+y;
}

int main() {

    constexpr int a{add(10,20)}; // This will evaluate
    cout << a << "\n";

    cout << add(10,20) << "\n"; // This will evaluate

    int b{20};
    cout << add(10,b); //This will not evaluate.
    return 0;
}
#+end_src
* Compound data types
:PROPERTIES:
:ID: Compound data types
:END:

#+begin_mindmap
   ╭─ Functions
   ├─ C-style arrays
   ├─ Pointer Types ┬─ Pointer to Object
   │                ╰─ pointer to function
   ├─ Pointer to member types ┬─ pointer to data member
   │                          ╰─ pointer to member function
«» ┼─ Reference types ┬─ L-value references
   │                  ╰─ R-value references
   ├─ Enumerated Types ┬─ Unscoped enumerations
   │                   ╰─ Scoped enumerations
   │              ╭─ Structs
   ╰─ Class Types ┼─ Classes
                  ╰─ Unions
#+end_mindmap

** L-value references
:PROPERTIES:
:ID:       d46624f3-8fc2-47a4-a8a4-2e9fc383bf7f
:END:
*** Non-const L value references
:PROPERTIES:
:ID:       3e48fd10-66f1-4f0c-88c0-fde9e796e724
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{2};
    int& y{x};
    cout << y << "\n";
    cout << x << "\n";

    x = 4;
    cout << y << "\n";
    cout << x << "\n";

    y = 5;
    cout << y << "\n";
    cout << x << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 2
: 2
: 4
: 4
: 5
: 5
*** Const L-value referencs
:PROPERTIES:
:ID:       673d6af3-7c66-4f0b-8f1d-4017bb8e2c10
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {

    const int x {2};
    const int& ref{x};

    cout << ref << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 2

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{2};
    const int& ref{x};

    cout << ref << "\n";
    cout << x << "\n";

    x = 3;      // Modified by variables.
    cout << ref << "\n";

    ref = 4;    // Cannot be modified by ref since it is const
    cout << ref << "\n";

    return 0;
}
#+end_src

#+RESULTS:

If we initialize lvalue const reference to rvalue.
Then a temporary object is created with rvalue and reference to const is bound to that temporary object.
Temporary objects are destroyed at the end of the statement.
But this creates a dangling ref so that compilers extend the lifetime of temporary objects to match the lifetime of ref.

Non-const lvalue references require an lvalue (an object with a persistent memory address) because they are designed to allow modification of the referenced object.  Rvalues (such as temporary objects or literals) do not have a persistent memory address and are immutable; binding a non-const reference to them would allow modifications to an object that is immediately destroyed or cannot be changed, leading to undefined behavior or logical errors.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    const int& ref{2};
    cout << ref << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 2

with diif data types.
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    char alp{'T'};

    const int& ref{alp};

    cout << ref << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 84

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    double x {5};
    const int& ref{x};
    cout << ref << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 5
** R-value refernces
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int& rvalueref = 5; // we cannot do this. Because we are assigning lvalueref to rvalue;
    int&& rvalueref = 5; // rvalue ref can be done like this
    cout << rvalueref << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 5

** Pass by reference
:PROPERTIES:
:ID: Pass by reference
:END:

#+begin_src cpp :results output
#include <iostream>
#include <string>
using namespace std;

void printname(string x)
{
    cout << x << "\n" ;
}

int main() {

    string name {"Shiva"};

    printname(name);

    return 0;
}
#+end_src

#+RESULTS:
: Shiva

Although the above program works fine.It is inefficent to make a copy of a string and will be destroyed  after the function.
So we use pass by reference.

#+begin_src cpp :results output
#include <iostream>
#include <string>
using namespace std;

void printname(string& ref)  //here we ref to name instead of making a copy
{
    cout << ref << "\n";
    ref = "Shiva";
    cout << ref << "\n";
}

int main() {
    string name{"Prasad"};
    printname(name);

    return 0;
}
#+end_src

#+RESULTS:
: Prasad
: Shiva

#+begin_src cpp :results output
#include <iostream>
using namespace std;
void passbyvalue(int x)
{
    cout << &x << "\n";
}

void passbyreference(int& x)
{
    cout << &x << "\n";
}
int main() {
    int x{2};
    cout << &x << "\n";
    passbyvalue(x);
    passbyreference(x);
    return 0;
}
#+end_src

#+RESULTS:
: 0x7ffc696819a4
: 0x7ffc6968198c
: 0x7ffc696819a4

Here we can notice the address of passbyreference and original varible is same.

** pass by const lvalue reference
:PROPERTIES:
:ID: pass by const lvalue reference
:END:
Unlike non-const lvalue reference for which we can bind to modifiable lvalues.
pass by const lvalue reference can be bind to modifiable, non-modifiable lvalues and rvalues.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

void print(const int& ref)
{
    cout << ref << "\n";
}

int main() {

    int x{2};  // we can pass nonconst varibales (modifiable)
    print(x);

    const int y{3};  // we can pass const varibales (non-modifiable)
    print(y);

    print(4);  // we can pass literal

    return 0;
}
#+end_src

#+RESULTS:
: 2
: 3
: 4

** why prefer std::string_view to const std::string&
:PROPERTIES:
:ID: why prefer std::string_view to const std::string&
:END:

| Argument Type          | std::string_view parameter | const std::string& parameter                 |
|------------------------+----------------------------+----------------------------------------------|
| std::string            | Inexpensive conversion     | Inexpensive reference binding                |
| std::string_view       | Inexpensive copy           | Expensive explicit conversion to std::string |
| C-style string/literal | Inexpensive conversion     | Expensive conversion                         |

#+begin_src cpp :results output
#include <iostream>
#include <string>
#include <string_view>

void printSV(std::string_view sv)
{
    std::cout << sv << '\n';
}

void printS(const std::string& s)
{
    std::cout << s << '\n';
}

int main()
{
    std::string s{ "Hello, world" };
    std::string_view sv { s };

    // Pass to `std::string_view` parameter
    printSV(s);              // ok: inexpensive conversion from std::string to std::string_view
    printSV(sv);             // ok: inexpensive copy of std::string_view
    printSV("Hello, world"); // ok: inexpensive conversion of C-style string literal to std::string_view

    // pass to `const std::string&` parameter
    printS(s);              // ok: inexpensive bind to std::string argument
    printS(sv);             // compile error: cannot implicit convert std::string_view to std::string
    printS(static_cast<std::string>(sv)); // bad: expensive creation of std::string temporary
    printS("Hello, world"); // bad: expensive creation of std::string temporary

    return 0;
}
#+end_src

** Pointers
:PROPERTIES:
:ID:       6c8fabe5-ab23-4a14-85da-a530791a14f5
:END:
*** Deference operator
:PROPERTIES:
:ID: Deference operator
:END:
& is address-of operator which returns address of object.
While * is used to return value at a given memory address as an lvalue.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{1};

    cout << x << "\n";
    cout << &x << "\n";  // gives address
    cout << *(&x) << "\n";  // gives value at that address

    return 0;
}
#+end_src

#+RESULTS:
: 1
: 0x7fff38edddc4
: 1
*** Pointer
:PROPERTIES:
:ID: Pointer
:END:

A Pointer is an object that holds a memory address as its value. This allows us to store the address of some other objects to use later.

#+begin_src cpp :results output
int;  // a normal int
int&; // an lvalue reference to an int value

int*; // a pointer to an int value (holds the address of an integer value)
#+end_src

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{1};
    int* ptr{&x};
    cout << *ptr << "\n";
    *ptr = 2;
    cout << *ptr << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 1
: 2


| Pointers                                       | References                                   |
|------------------------------------------------+----------------------------------------------|
| It can change the varibale it is being pointed | It cannot be changed it is being refered to. |
| Pointers are objects                           | References are not objects.                  |
| Pointers can point to nothing                  | References must always bound to an object    |
| Pointers are not required to be initialized    | References must be initialized               |

- The size of the pointer is independent to it is being pointed, instead it depends on architecture of the computer.
- In a 32 bit computer 4 bytes are taken and in 64 bit computer 8 bytes are taken.

*** Address of operator returns a pointer
:PROPERTIES:
:ID: Address of operator returns a pointer
:END:
The address of operator doesnt returns address of its operand as literal, Instead it returns a pointer to the operand.

#+begin_src cpp :results output
#include <iostream>
#include <typeinfo>
using namespace std;

int main() {
    int x{1};

    cout << typeid(x).name() << "\n";
    cout << typeid(&x).name() << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: i
: Pi
*** null pointers as boolean values
:PROPERTIES:
:ID: null pointers as boolean values
:END:

- Null pointer is implicitly converted to boolean value false.
- Not Null pointer is implicitly converted to boolean value true.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int* ptr{};

    if(ptr) {
        cout << "Not Null" << "\n";
    }else {
        cout << "Null" << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: Null
*** pointer to const
:PROPERTIES:
:ID:       819dd8ff-8d93-490b-80ad-ba2fc8e45b09
:END:

1. If the object is const then the pointer should be const.
2. If the object is non-const, we can still point a const pointer to it but we cannot change the value of object by deferencing pointer.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {

    const int x{2};
    const int* ptr{&x};

    cout << *ptr << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 2

we also make pointer ifself const. i.e, it doesnt change the address it is holding.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{1};

    int* const ptr{&x};
    cout << *ptr << "\n";

    int y{2}
    ptr = &y; // Do not possible

    return 0;
}
#+end_src

Const pointer to a const value
With this we cannot change the address and the value.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int x{2};
    const int* const ptr{&x};

    cout << *ptr << "\n";

    int y{3};

    ,*ptr = 3; // Not possible
    ptr = &y
    return 0;
}
#+end_src

#+RESULTS:
*** pass by address
:PROPERTIES:
:ID:       5c717542-3df3-46cb-ba1f-efb5f1a0e718
:END:

#+begin_src cpp :results output
#include <iostream>
#include <string>

void printByValue(std::string val) // The function parameter is a copy of str
{
    std::cout << val << '\n'; // print the value via the copy
}

void printByReference(const std::string& ref) // The function parameter is a reference that binds to str
{
    std::cout << ref << '\n'; // print the value via the reference
}

void printByAddress(const std::string* ptr) // The function parameter is a pointer that holds the address of str
{
    std::cout << *ptr << '\n'; // print the value via the dereferenced pointer
}

int main()
{
    std::string str{ "Hello, world!" };

    printByValue(str); // pass str by value, makes a copy of str
    printByReference(str); // pass str by reference, does not make a copy of str
    printByAddress(&str); // pass str by address, does not make a copy of str

    return 0;
}
#+end_src
** Operator overloading
:PROPERTIES:
:ID:       91f9c503-f53a-4d51-a398-10c9fe7be9dc
:END:

Operator overloading = writing your own function that runs when someone uses +, ==, <<, etc. on your custom data type.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Point {
    int x;
    int y;
};

Point operator+(Point a, Point b) {
    Point result;
    result.x = a.x + b.x;
    result.y = a.y + b.y;

    return result;
}

int main() {
    Point P1{1,2};
    Point P2{4,5};
    Point P3;
    P3 = P1 + P2;
    cout << P3.y;
    return 0;
}
#+end_src

#+RESULTS:
: 7


#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Point {
    int x;
    int y;
};

bool operator==(Point a, Point b) {
   return (a.x == b.x) && (a.y == b.y);
}

int main() {
    Point p1{1,2};
    Point p2{1,2};
    if(p1 == p2)
        cout << "Equal" << "\n";
    else
        cout << "Not equal" << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: Equal

#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Point {
    int x; int y;
};

ostream& operator+(ostream& hi, Point& p) {
    hi << "X: " << p.x << " Y: " << p.y;
    return hi;
}

int main() {
    Point P1{1,2};
    cout + P1;
    return 0;
}
#+end_src

#+RESULTS:
: X: 1 Y: 2

** Enumerations
:PROPERTIES:
:ID:       596bd0f2-f28c-40bb-9ec0-8de3600fc987
:END:
Enumerations are implicitly constexpr.
*** Unscoped Enumerations
:PROPERTIES:
:ID: Unscoped Enumerations
:END:
Each enumeration is numbered from 0. We can explicitly number a enumeration, any undefined enumeration will be given one value greater than the previous one.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

enum Color {red,white, yellow};

int main() {
    Color car{white};
    cout << car << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 1

#+begin_src cpp :results output
#include <iostream>
using namespace std;

namespace nothing{
    enum Color {
        red,
        white,
        yellow,
    };
}

int main() {

    nothing::Color apple{nothing::red}; //apple will store integral value 0.

    cout << apple << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 0

#+begin_src cpp :results output
#include <iostream>
using namespace std;
enum color {
    red,
    white,
    yellow,
};

int main() {
    color apple{static_cast<color>(2)};
    cout << apple << "\n";
    Return 0;
}
#+end_src

#+RESULTS:
: 2

#+begin_src cpp :results output
#include <iostream>
#include <string_view>
using namespace std;

enum Color {red, white, yellow, blue};

constexpr string_view Print(Color ref)
{
    switch(ref) {
        case red: return "red";
        case white: return "white";
        case yellow: return "Yellow";
        default: return "Error";
    }
}

int main() {
    constexpr Color apple{yellow};
    cout << Print(apple) << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: Yellow

#+begin_src cpp :results output
#include <iostream>
#include <string_view>
using namespace std;

namespace nothing {
    enum Color {white, yellow, red};
};

constexpr string_view print(nothing::Color ref) {
    switch(ref){
        case white: return "white";
        case yellow: return "yellow";
        case red: return "red";
        default: return "Error";
    }
}


int main() {

    nothing::Color jersey{nothing::white};

    cout << print(jersey) << "\n";

    return 0;
}
#+end_src
*** scoped Enumerations
:PROPERTIES:
:ID: Scoped Enumerations
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

enum class Color {white, red, green};

int main() {
    Color color {Color::white};
    cout << color << "\n";
    return 0;
}
#+end_src

#+RESULTS:


#+begin_src cpp :results output
#include <iostream>
using namespace std;

enum class cartoon {doreman, shinchan, bheem};

int main() {

    using enum cartoon;

    cartoon fav{shinchan};

    return 0;
}
#+end_src
** Struct
:PROPERTIES:
:ID: struct
:END:

A struct is a program defined data type that allows us to bundle multiple variables together into a single type.

1. Defining a struct
#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Employee {
    int id;
    int age;
    double salary;
}

int main() {

    return 0;
}
#+end_src

By declaring the struct it cannot occupy any space. But by initialization the object does.

Variables inside a group are called members.

2. Initialing a object.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Employee {
    int id;
    int age;
    double salary;
}

int main() {
    Employee gachibowli{};  // Object as created with the three varibles.
    return 0;
}
#+end_src

3. To access a specific member we use member selecion operator (.).

#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Employee {
    int id;
    int age;
    double salary;
};

int main() {
    Employee gachibowli{};  // Object as created with the three varibles.

    gachibowli.id = 1;
    cout << gachibowli.id << "\n";

    gachibowli.age = 67;
    cout << gachibowli.age << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 1
: 67


#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Point {
    int x{};
    int y{};
};

struct triangle {
    Point a{};
    Point b{};
    Point c{};
};

int main() {

    Point a{2,3};
    Point b{3,4};
    Point c{4,5};

    triangle tri{a,b,c};

    triangle* ptr(&tri);

    cout << (ptr -> c).x << "\n";

    return 0;
}
#+end_src

#+RESULTS:
: 4
** Classes (OOP)
:PROPERTIES:
:ID:       cd2cfe93-4c05-43da-aced-0b891ab966dd
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Date {
public:
    int m_day{};
    int m_month{};
    int m_year{};
};

void printdate(Date& date)
{
    cout << date.m_day << "/" << date.m_month << "/" << date.m_year << "\n";
}
int main() {
    Date date{19, 06, 2026};
    printdate(date);
    return 0;
}
#+end_src

*** member functions
:PROPERTIES:
:ID: member function
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Date {
public:
    int m_day{};
    int m_month{};
    int m_year{};

    void print() {
        cout << m_day << "/" << m_month << "/" << m_year << "\n";
    }
};

int main() {
    Date date{19, 06, 2026};

    date.print();
    return 0;
}
#+end_src

#+RESULTS:
: 19/6/2026

- member function with const object

  if the object is const then the member fucntion should also have to be a member fucntion.

#+begin_src cpp :results output
#include <iostream>
using namespace std;
class Car
{
public:
    int model{};
    int color_code{};

    void print() const {
       cout << "Model: " << model << " Color Code: " << color_code << "\n";
    }
};
int main() {

    const Car swift{1,79879};

    swift.print();

    return 0;
}
#+end_src

#+RESULTS:
: Model: 1 Color Code: 79879
\j*** access functions
 #+begin_src cpp :results output
#include <iostream>
usjing namespace std;

class House {
    int m_house_no{21};
    int m_members{9};

public:
    void print() {
        cout << m_house_no << " " << m_members << "\n";
    }

    int gethouseno() const {return m_house_no;}
    void sethouseno(int houseno) {m_house_no = houseno;}

    int getmembers() const {return m_members;}
    void setmembers(int members) {m_members = members;}
};

int main() {

    House my_house{};

    my_house.print();

    my_house.sethouseno(44);
    my_house.setmembers(4);

    cout << my_house.gethouseno() << "\n";
    cout << my_house.getmembers() << "\n";

    return 0;
\}
#+end_src
*** returning data members by lvalue reference
:PROPERTIES:
:ID:       d4ed5775-4900-4c30-aec6-ca6815d371b8
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

class House {
    int m_houseno{12};
    int m_members{3};

public:
    void print() {
        cout << m_houseno << " " << m_members << "\n";
    }

    int& gethouseno() {return m_houseno;}
};

int main() {
    House myhouse{};
    cout <<  myhouse.gethouseno();
    return 0;
}
#+end_src

#+RESULTS:
: 12

#+begin_src cpp :results output
#include <iostream>
#include <string>
using namespace std;
class Bike{
    string m_name{};
public:

    void setname(string_view name) {m_name = name;}

    string getname_byvalue() {
        return m_name;
    }

    string& getname_byreference() {
        return m_name;
    }
};

int main() {
    Bike bmw{};
    cout << bmw.getname_byvalue() << "\n";
    bmw.setname("BMW");
    cout << bmw.getname_byreference() << "\n";
    return 0;
}
#+end_src
*** constructor
:PROPERTIES:
:ID:       7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Foo{
    int m_a;
    int m_b;

public:
    Foo(int a,int b) {
        this->m_a = a;
        this->m_b = b;
    }

    //Foo(int a,int b) : m_a {a}, m_b {b}; {}

    void print() {
        cout << m_a << " " << m_b << "\n";
    }
};

int main() {
    Foo f{3,9};
    f.print();
    return 0;
}
#+end_src

1. A constructor is a special member function invoked when an object of class is created. It shares same name as class and has no return type.
2. It is responsible for initializing data members and setting initial state.


Delegating constructors
Constructors are allowed to delegate (transfer responsibility for) initialization to another constructor from the same class type. This process is sometimes called constructor chaining and such constructors are called delegating constructors.

   #+begin_src cpp :results output
#include <iostream>
using namespace std;

class Employee{
    string m_name{};
    int m_id{};
public:
    Employee(string name) :Employee(name, 0) {}

    Employee(string name, int id) : m_name {name}, m_id {id} {}

    void print() {
        cout << m_name << " " << m_id << "\n";
    }
};

int main() {
    Employee e1{"shiva"};
    e1.print();

    Employee e2{"shiva",9};
    e2.print();
    return 0;
}
#+end_src

#+RESULTS:
: shiva 0
: shiva 9

Reducing construtor using default arguments
   #+begin_src cpp :results output
#include <iostream>
using namespace std;

class Employee{
    string m_name{};
    int m_id{};
public:
    Employee(string name, int id = 0) : m_name {name}, m_id {id} {}

    void print() {
        cout << m_name << " " << m_id << "\n";
    }
};

int main() {
    Employee e1{"shiva"};
    e1.print();

    Employee e2{"shiva",9};
    e2.print();
    return 0;
}
#+end_src

#+RESULTS:
: shiva 0
: shiva 9

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Ball {
    string m_color{"black"};
    double m_radius{10.0};
public:
    Ball() {
        print();
    }

    Ball(string color) : m_color {color} {
        print();
    }

    Ball(double radius) : m_radius {radius} {
        print();
    }

    Ball(string color, double radius) : m_color {color} , m_radius {radius} {
        print();
    }

    void print() {
        cout << "Ball(" << m_color << ", " << m_radius << ")" <<  "\n";
    }
};
int main() {
    Ball def{};
    Ball blue("blue");
    Ball twenty{20};
    Ball bluetwenty{"blue", 20};
    return 0;
}
#+end_src

#+RESULTS:
: Ball(black, 10)
: Ball(blue, 10)
: Ball(black, 20)
: Ball(blue, 20)

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Ball{
    string m_name{};
    double m_radius{};
public:
    Ball(double radius) : Ball{"black", radius} {}

    Ball(string name = "black",double radius = 10.0) : m_name {name} , m_radius {radius} {print();}

    void print() {
        cout << "Ball(" << m_name << ", " << m_radius << ")" <<  "\n";
    }
};

int main() {
    Ball def{};
    Ball blue("blue");
    Ball twenty{20};
    Ball bluetwenty{"blue", 20};
    return 0;
}
#+end_src

#+RESULTS:
: Ball(black, 10)
: Ball(blue, 10)
: Ball(black, 20)
: Ball(blue, 20)
*** temporary object
:PROPERTIES:
:ID:       db0d93d4-f8b4-421c-aa05-cd9097953cbd
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Point{
    int m_x{};
    int m_y{};

public:
    Point(int x, int y) : m_x {x} , m_y {y} {};

    int x() {return m_x;}
    int y() {return m_y;}
};

void print(Point p) {
    cout << p.x() << " " << p.y() << "\n";
}

int main() {
    Point p1{1,2};
    print(p1);
    print(Point {3,4}  );
    print({1,2});
    return 0;
}
#+end_src

#+RESULTS:
: 1 2
: 3 4
: 1 2

- callling a constructor in a function creates a temporary object
*** delegating [[id:7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c][constructor]]
:PROPERTIES:
:ID:       75ef050f-974c-4aee-aaef-fb6c29857536
:END:
To make one [[id:7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c][constructor]] delegate to another construtor simply call the constructor in member initialization list of another [[id:7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c][constructor]].

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Employee {
    string m_name{};
    int m_age{};
public:
    Employee(string name) : Employee(name, 0) {}

    Employee(string name, int age) : m_name {name} , m_age {age} {cout << m_name << " " << m_age << "\n";}
};

int main() {
    Employee e1{"Shiva"};
    Employee e2{"PRASAD",2};
    return 0;
}
#+end_src

#+RESULTS:
: Shiva 0
: PRASAD 2
*** copy [[id:7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c][constructor]]
:PROPERTIES:
:ID:       6f470fe6-37ac-4cc1-97aa-bb5d0fdd4e90
:END:

A copy construtor is a construtor that is used to initialize an object using an existing object.

A copy [[id:7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c][constructor]] is implicitly created by compiler when we create a object using another object like in below. Although we can create copy [[id:7eefd7b1-cbe6-4f3e-8cdf-13c2ec75f43c][constructor]] manually.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Number {
    int m_a{};
    int m_b{};
public:
    Number(int a, int b) : m_a {a}, m_b{b} {}

    void print() {
        cout << m_a << " " << m_b << endl;
    }
};

int main() {
    Number x{3,5};
    Number y{x};
    x.print();
    y.print();
    return 0;
}
#+end_src

#+RESULTS:
: 3 5
: 3 5

initiallzing a copy construtor manually.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Number {
    int m_a{};
    int m_b{};
public:
    Number(int a, int b) : m_a {a}, m_b{b} {}

    Number(Number& num) : m_a {num.m_a} , m_b {num.m_b} {
        cout << "Copy constructor is called" << "\n";
    }

    void print() {
        cout << m_a << " " << m_b << endl;
    }
};

int main() {
    Number x{3,5};
    Number y{x}; // here copy construtor is called
    x.print();
    y.print();
    return 0;
}
#+end_src

#+RESULTS:
: Copy constructor is called
: 3 5
: 3 5

creating a default copy construtor using *default*

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Fraction {
    int m_a{};
    int m_b{};
public:
    Fraction(int a, int b) : m_a{a}, m_b {b} {}

    Fraction(const Fraction& fraction) = default;

    void print() {
        cout << m_a << " " << m_b << "\n";
    }
};

int main() {
    Fraction f{1,2};
    Fraction f1{f};
    f.print();
    f1.print();
    return 0;
}
#+end_src

#+RESULTS:
: 1 2
: 1 2

using = delete to prevent copies

#+begin_src cpp :results output
#include <iostream>

class Fraction
{
private:
    int m_numerator{ 0 };
    int m_denominator{ 1 };

public:
    // Default constructor
    Fraction(int numerator=0, int denominator=1)
        : m_numerator{numerator}, m_denominator{denominator}
    {
    }

    // Delete the copy constructor so no copies can be made
    Fraction(const Fraction& fraction) = delete;

    void print() const
    {
        std::cout << "Fraction(" << m_numerator << ", " << m_denominator << ")\n";
    }
};

int main()
{
    Fraction f { 5, 3 };
    Fraction fCopy { f }; // compile error: copy constructor has been deleted

    return 0;
}
#+end_src

*** pass by value and copy construtor
:PROPERTIES:
:ID:       5dbdde02-e9f6-425f-943b-82d9f409f40c
:END:

when we pass an object by value to a function if the argument and parameter are of same class type then implicitly copy construtort is called.

in the beow code when an object is passed as value to a function then explicitly created copy construtor is invoked.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Number {
    int m_a{};
    int m_b{};
public:
    Number(int a, int b) : m_a {a}, m_b{b} {}

    Number(Number& num)  : m_a {num.m_a} , m_b {num.m_b} {
       cout << "copy construtor is called" << "\n";
   }

    void print() {
        cout << m_a << " " <<  m_b << "\n";
    }
};

void fun(Number x) {
    x.print();
}

int main() {
    Number x{12,3};
    fun(x);
    return 0;
}
#+end_src

#+RESULTS:
: copy construtor is called
: 12 3
*** array of object
:PROPERTIES:
:ID:       4b4d1504-5ce3-4eb0-b9e4-f204de563916
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Student{
public:
    string name;
    int age;
    Student() {}
    Student(string s, int a) : name{s},age{a} {}
};

int main() {
    Student s[10];
    s[0].name = "shiva";
    s[0].age = 19;
    s[1].name = "Prasad";
    s[1].age = 19;
    s[2].name = "shiva";
    s[2].age = 19;
    for(int i =0;i<3;i++) {
        cout << s[i].name <<  " " <<  s[i].age << '\n';
    }
    return 0;
}
#+end_src

#+RESULTS:
: shiva 19
: Prasad 19
: shiva 19

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Student{
public:
    string name;
    int age;
    Student() {}
    Student(string s, int a) : name{s},age{a} {}
};

int main() {
    Student s[] = {
        {"shiva",1},
        {"Prasad",2},
        {"sunny",3},
    };

    for(int i =0;i<3;i++) {
        cout << s[i].name <<  " " <<  s[i].age << '\n';
    }
    return 0;
}

#+end_src

#+RESULTS:
: shiva 1
: Prasad 2
: sunny 3

*** Copy elison
:PROPERTIES:
:ID:       cb683dcd-2755-4ed2-85a8-c1ea0626e6b2
:END:
Copy elision is a compiler optimization technique that allows the compiler to remove unnecessary copying of objects. In other words, in cases where the compiler would normally call a copy constructor, the compiler is free to rewrite the code to avoid the call to the copy constructor altogether. When the compiler optimizes away a call to the copy constructor, we say the constructor has been elided.
*** User defined conversions
:PROPERTIES:
:ID:       2919e6a9-86ae-4c40-a82f-8ad364b0849c
:END:

here even though we the function *gets* has parameter Numbers class type in arguments we gave int. So the compiler implicitly converts the types.
These type of functions are called *user defined functions*.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Numbers {
    int m_a{};
public:
    Numbers(int a) : m_a {a} {}

    void print() {
        cout << m_a << "\n";
    }

};

void gets(Numbers num) {
    num.print();
}

int main() {
    gets(2);
    return 0;
}
#+end_src

#+RESULTS:
: 2
*** constexpr member functions
:PROPERTIES:
:ID:       ed2b9127-74e0-4db5-9d00-2a70e8ae9217
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Numbers {
    int m_a{};
    int m_b{};

    constexpr void print() {
        cout << m_a << " " << m_b << "\n";
    }
};

int main() {
    Numbers num{1,2};
    num.print();

    constexpr num1{3,4};
    num1.print();

    return 0;
}
#+end_src

#+RESULTS:
: 1 2

This works for aggregate functions functions like *struct* but not for *class*

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Numbers {
    int m_a{};
    int m_b{};

public:
    Numbers(int a, int b) : m_a{ a } , m_b {b} {}

    constexpr void print() {
        cout << m_a << " " << m_b << "\n";
    }
};
int main() {
    constexpr Numbers num{21,2};
    num.print() ;
    return 0;
}
#+end_src

#+RESULTS:

here when object is created the construtor is called which is of type class Numbers which is not constexpr so it doesnt run at runtime.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Numbers {
    int m_a{};
    int m_b{};

public:
    constexpr Numbers(int a, int b) : m_a{ a } , m_b {b} {}

    constexpr void print() {
        cout << m_a << " " << m_b << "\n";
    }
};
int main() {
    constexpr Numbers num{21,2};
    num.print();
    return 0;
}
#+end_src

#+RESULTS:

😭


#+begin_src cpp :results output
#include <iostream>
using namespace std;

class so{
    int m_a{};
public:
    so(int a) : m_a {a} {}

    void print() {
        cout << m_a << "\n";
    }
};

int main() {
    so a{1};
    a.print();

    so* b{&a};
    b->print();
    return 0;
}
#+end_src

#+RESULTS:
: 1
: 1

*** the hidden this pointer
:PROPERTIES:
:ID:       0027b492-1478-49c8-8761-9b7a46f57973
:END:

Inside every member function the keyword this is a const pointer that holds the address of current of object.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class numbers{
    int m_a{};
public:
    numbers(int a) :m_a {a} {}

    void print() {
        cout << this->m_a<< "\n";
    }
};

int main() {
    numbers n{1};
    n.print(&n);
    return 0;
}
#+end_src

#+RESULTS:

in the above the code can work simply if we put *m_a* instead of *this->m_a*
but this proves that there is a pointer of type numbers which stores address of object. so by using this->m_a it can access the m_a member.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Simple{
   int m_a{};
public:
    void set_a(int a) {
        m_a = a;
    }

    int get_a() {
        return m_a;
    }
};

int main() {
    Simple x{};
    x.set_a(2);
    cout << x.get_a() << "\n";
    return 0;
}
#+end_src

#+RESULTS:
: 2

here the compiler rewrites *x.set_a(2)* as *Simple::set_a(&Simple, 2)* internally

then the set_a function also changes in the class as

*void set_a(int a) {m_a = a}* ----------->>  static void set_a(Simple* const this, int a) {this->m_a =a;}

1. When we call simple.set_a(2), the compiler actually calls Simple::set_a(&simple, 2) and simple is passed by address to the function
2. The function has hidden parameter named *this* which receives the address of simple.
3. member variables inside set_a() are prefixed with *this->* which points to simple. So when compiler evaluates this->m_a, its actually resolving to simple.m_a

- Each member function has single this pointer parameter that points to the implicit object.

  Explicitly referencing this

  #+begin_src cpp :results output
#include <iostream>
using namespace std;

struct something {
    int a{};

    void set_a(int a) {
        this->a = a;
    }

    int get_a() {
        return a;
    }
};

int main() {
    something a{};
    a.set_a(1);
    cout << a.get_a();
    return 0;
}
#+end_src

#+RESULTS:
: 1

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class something{
    int a{};
public:
    void get() {
        cout << *this << "\n";
    }
};

int main() {
    int a{1};
    int* ptr{&a};
    cout << *ptr << "\n";
    something s{};
    s.get();
    return 0;
}
#+end_src

#+RESULTS:
*** member function chaining using *this
:PROPERTIES:
:ID:       c6d769ca-d2a1-45fd-99c3-4db1f9010bcd
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Cal{
    int m_a{0};
public:
    void add(int a) {m_a += a;}
    void sub(int a) {m_a -= a;}
    void mul(int a) {m_a *= a;}

    int get() {
        return m_a;
    }
};

int main() {
    Cal cal{};
    cal.add(3);
    cal.sub(1);
    cal.mul(4);
    cout << cal.get();
    return 0;
}
#+end_src

#+RESULTS:
: 8

Here to add, sub, and mul we need to call three diffrent member fuuntions seperating but with member fucntion chaining we can do it in a single line.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Cal{
    int m_a{0};
public:
    Cal& add(int a) {
        m_a += a;
        return *this;
    }

    Cal& sub(int a) {
        m_a -= a;
        return *this;
    }

    Cal& mul(int a) {
        m_a *= a;
        return *this;
    }

    int get() {
        return m_a;
    }

    void reset() {
        ,*this = {};
    }
};

int main() {
    Cal a{};
    a.add(3).sub(1).mul(3);
    cout << a.get() << "\n";

    a.reset();

    cout << a.get();
    return 0;
}
#+end_src

#+RESULTS:
: 6
: 0

here first add(3) runs and adds value 3 to m_a then it returns reference of the Cal object so
a.add(3).sub(1).mul(3) ------> a.sub(1).mul(3)

- Here we can reset the value of members using a member fucntion reset by *this = {}
- it creates a temporary Cal using default values of members and assigns it to current object.
*** Destructor
:PROPERTIES:
:ID:       727d415a-b93b-4d78-b574-c737c4e976fb
:END:
- Destructor is used for cleaning
- It is called automatically when an object of a class is destroyed.
- It doesnt have any arguments.
- It doesnt have any return type.
- It has name name as class preceding with a tilde(~).
- Although we can call destructor explicitly it is called automatically almost every time.
- If we dont not declare a dedtructot the compiler will implicitly declare a destructor with empty body.

  #+begin_src cpp :results output
#include <iostream>
using namespace std;

class Simple{
    int m_id{};
public:
    Simple(int id)  : m_id {id} {}

    ~Simple() {
        cout << "Destructor" << m_id << "\n";
    }

};

int main() {
    Simple s1(1);
    {
        Simple s2(2);
    }//s2 dies here so destructor of s2 is called first.
    return 0;
}//s1 dies here.
#+end_src

#+RESULTS:
: Destructor2
: Destructor1
*** static member variables and functions
:PROPERTIES:
:ID:       2bb1cb78-ea45-49ed-b90a-ff2b263501ba
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Something{
    static int a;
};

int Something::a{1};

int main() {

    Something something1{};
    Something something2{};

    something1.a = 2;

    cout << something1.a << "\n";
    cout << something2.a << "\n";

    return 0;
}
#+end_src

Here we can see eventhough we changed the value of a for *something1* it has also changed for *something2*

*Static members are not associated with class objects* - we know that when we create a object it occupies memory for it, but when it comes to static member variables it will be created at the start of the program and destroyed at the program so it is independent of class object.

*When can say that - static members are global variables that live inside the scope region of a class*

Because it is independent of object we can access it with class name and scope resolution operator. just like above

It is declared as forward declare and the static members are accessed independent of access control like *private* *protected*, because the forward definations are not considered a way to access.

If we include a header file which has class definations there wont be initialized.
We have to initialize using access specifier but we can initialize to a static member if is inline.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

struct Something{
    static inline int a{1};
};

int main() {
    Something something{};
    cout << something.a;
    return 0;
}
#+end_src

#+RESULTS:
: 1

Consider this

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Something {
    static inline int m_a{1};

public:
    int get() {
        return m_a;
    }
};

int main() {
    Something s{};
    cout << s.get();
    return 0;
}
#+end_src

#+RESULTS:
: 1

even though this works for getting the value it need to create a object.
for this reason we use static member functions.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Something{
    static inline int m_a{1};
public:
    static int get() {
        return m_a;
    }
};

int main() {
    cout << Something::get();
    return 0;
}
#+end_src

#+RESULTS:
: 1

here we accessed a private data member using static member function without creating an object.

- static member functions do not have *this pointer.
*** friend non-member functions
:PROPERTIES:
:ID:       de60d992-7ba5-4cf8-99ba-5ef22151eba3
:END:

Friend function or member is used for access private or protected data of a class to another class or function.

*friend is a class or function (member or non-member) that has been granted full access to the private and protected members of another class.*

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Something{
    int m_a{};
public:
    Something(int a) : m_a {a} {}

    friend void print(const Something& something); //declaration of friend function
};


void print(const Something& something) {
    cout << something.m_a;
}

int main() {
    Something nothing{1};
    print(nothing);
    return 0;
}
#+end_src

#+RESULTS:
: 1

defining friend non-member inside a class

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Something{
    int m_a{};
public:
    Something(int a) : m_a {a} {}

    friend void print(const Something& something) {
        cout << something.m_a;
    }
};

int main() {
    Something nothing{1};
    print(nothing);
    return 0;
}
#+end_src
*** friend class and friend member function
:PROPERTIES:
:ID:       246e1d8a-20cb-44b9-8832-7fcf8c38e48f
:END:
 A friend Class is that can access private and protected member of another class.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Storage{
    int m_d{};
    int m_n{};
public:
    Storage(int d,int n) : m_d {d} , m_n {n} {}

    friend class Display;
};

class Display{
    bool first{};

public:
    Display(bool b) : first {b} {}

    void displaystorage(Storage& storage) {
        if(first) {
            cout << storage.m_d << " " << storage.m_n << "\n";
        }else {
            cout << storage.m_n<< " " << storage.m_d << "\n";
        }
    }
};

int main() {
    Storage storage{10,20};
    Display display{false};

    display.displaystorage(storage); //here we are acessing the members of class Storage from class display

    return 0;
}
#+end_src

friend member funtion - instead of making an entire class friend we can make a function from another class a friend.
this can be done like this

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Display {};

class Storage{
    int m_a{};
    int m_n{};

public:
    Storage(int a, int n) : m_a {a} , m_n{n} {}

    friend void Display::displaystorage(const Storage& storage);
};

class Display{
    bool is{};
public:

    Display(bool b) : b{is} {}

    void displaystorage(const Storage& storage) {
        if(is) {
            cout << m_a << " " << m_n << "\n";
        }else {
            cout << m_n << " " << m_a << "\n";
        }
    }
};

int main() {

    Storage storage{10,20};
    Display display{true};

    display.displaystorage();

    return 0;
}
#+end_src

This doesnt work because the compiler will throw an error the it hasnt seen full defination of class Display

Instead we can do something like this

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Storage;

class Display{
   bool is{};
public:
    Display(bool b) : is{b} {}
    void displaystorage(Storage& storage);  // This is the reason we farward declared class Storage.
};

class Storage{
    int m_n{};
    int m_a{};
public:
    Storage(int n, int a) : m_n{n} , m_a{a} {}

    friend void Display::displaystorage(Storage& storage);
};

void Display::displaystorage(Storage& storage) {
    if(is) {
        cout << storage.m_n << " " << storage.m_a << "\n";
    }else {
        cout << storage.m_a << " " << storage.m_n << "\n";
    }
}

int main() {
    Storage storage{10,20};
    Display display{false};
    display.displaystorage(storage);
    return 0;
}
#+end_src

#+RESULTS:
: 20 10

[[https://www.learncpp.com/cpp-tutorial/friend-classes-and-friend-member-functions/][Quiz]]

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Vector{
    double m_x{};
    double m_y{};
    double m_z{};
public:
    Vector(double x, double y, double z) : m_x{x}, m_y{y} , m_z{z} {}

    void print() {
        cout << "x: " << m_x << " y: " << m_y << " z: " << m_z << "\n";
    }

    friend class Point;
};

class Point{
    double m_x{};
    double m_y{};
    double m_z{};
public:
    Point(double x,double y,double z) :m_x {x}, m_y{y}, m_z{z} {}

    void print() {
        cout << "x: " << m_x << " y: " << m_y << " z: " << m_z << "\n";
    }

    void movebyvector(Point& point) {
        cout << point.m_x + m_x << " " << point.m_y + m_y << " " << point.m_z + m_z << "\n";
    }
};

int main() {
    Vector vector{1.2, 2.2, 3.4};
    Point point{2.3, 3.4, 4.9};
    point.movebyvector(point);
    return 0;
}
#+end_src

#+RESULTS:
: 4.6 6.8 9.8

* Dynamic arrays
:PROPERTIES:
:ID:       1242bc2a-31ab-446a-827f-634b0acc47e8
:END:
** Introduction to std::vector
:PROPERTIES:
:ID:       ab5728bc-2c84-427e-8be7-6a9cc16a0c40
:END:

#+begin_src cpp :results output
#include <iostream>
#include <vector>

int main() {
    std::vector<int> empty{};
    std::vector<int> whole{0,1,2,3};

    std::cout << whole[2];
    return 0;
}
#+end_src

#+RESULTS:
: 02

Containers typically have a special constructor called a list constructor that allows us to construct an instance of the container using an initializer list. The list constructor does three things:

1. Ensures the container has enough storage to hold all the initialization values (if needed).
2. Sets the length of the container to the number of elements in the initializer list (if needed).
3. Initializes the elements to the values in the initializer list (in sequential order).

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    const vector<int> arr{1,2};
    cout << arr[1];
    return 0;
}
#+end_src

#+RESULTS:

length using size() member function.

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector arr{1,2,3};
    cout << arr.size() << "\n";
    cout << size(arr);
    return 0;
}
#+end_src

#+RESULTS:
: 3
: 3

Since size() member function supports only unsigned numbers when we assign the length to a variable using size() it may result in signed/unsigned conversion warnings

Instead we cast using static cast

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector arr{1,2};
    //int length {arr.size()}; gives warning
    int length (static_cast<int>(arr.size()));
    cout << length;
    return 0;
}
#+end_src

#+RESULTS:
: 2

using ssize for length
- Since ssize is non-member function and returns lenght as long signed int we also need to cast this.j

  #+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector arr{1,2,3};
    int length {std::ssize(arr)};
    cout << length << "\n";
    return 0;
}
#+end_src

pass by reference

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

void fun(const vector<int>& arr) {
    cout << arr[0];
}

int main() {
    vector arr{1,2,3,4};
    fun(arr);
    return 0;
}
#+end_src

#+RESULTS:
: 1

we have to mention type of data in function parameter
we can use template

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;
template <typename T>
void fun(const vector<T>& arr) {
    cout << arr[0] << "\n";
}

int main() {
    vector arr1{1,2,3};
    vector arr2{1.2, 3.2};
    fun(arr1);
    fun(arr2);
    return 0;
}
#+end_src

#+RESULTS:
: 1
: 1.2

*** passing a std::vector using generic template or abbreviated function template
:PROPERTIES:
:ID:       3bce83e1-e5a7-4f8f-966f-95208dcdda80
:END:
we can also create a template that can accpet any type of object.

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;
template<typename T>

void print(const T& arr) {  // will accept any type of object that has an overload operator

    cout << arr[2] << "\n";
}

int main() {
    vector arr1{1,2,3};
    print(arr1);
    vector arr2{11.1,10.2,11.3};
    print(arr2);

    return 0;
}
#+end_src

#+RESULTS:
: 3
: 11.3

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

void print(const auto& arr) {
    cout << arr[0];
}

int main() {
    vector arr{1,2,3};
    print(arr);
    return 0;
}
#+end_src

#+RESULTS:
: 1

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;
template <typename T>
void print(const T& arr, int n) {
    if(n<arr.size()) {
        cout << arr[n] << "\n";
    }else {
        cout << "N should be less than the size of array" << "\n";
    }
}

int main() {
    vector arr{1,2,3,4};
    print(arr,5);

    vector arr1{4.5, 3.4, 6.7};
    print(arr1,2);
    return 0;
}
#+end_src
*** move semantics
:PROPERTIES:
:ID:       3ea4a6d2-e5fa-46bd-a7d5-6519af114de1
:END:
*Move semantics is an optimization that allow us, under certain circumstances, to inexpensively transfer ownership of some data members from one object to another object(rather than making a more expensive copy)*

- Normally when an object is being initialized with an object of the same type, copy semantic will be used.
*** arrays and loop
:PROPERTIES:
:ID:       764b4e33-2cc1-4dfa-884d-a5783b127126
:END:
#+begin_src cpp :results output
#include <iostream>
#include <vector>
#include <cstddef>
using namespace std;

void avg(vector<int>& arr){
    size_t length (arr.size());
    int sum = 0;
    for(size_t index = 0; index < length; ++index) {
        sum += arr[index];
    }
    int avg = sum / static_cast<int>(length);
    cout << avg << "\n";
}

int main() {
    vector arr{1,2,3,4,5,6,7};
    avg(arr);
    return 0;
}
#+end_src

#+RESULTS:
: 4
*** template arrays and loop
:PROPERTIES:
:ID:       d4e383bc-cad4-459c-b27f-61961dcfe55e
:END:
#+begin_src cpp :results output
#include <iostream>
#include <vector>
#include <cstddef>
using namespace std;
template <typename T>

void avg(vector<T>& arr) {
    size_t length {arr.size()};
    T sum = 0;

    for(size_t index = 0; index < length; ++index) {
        sum += arr[index];
    }
    T avg = sum / static_cast<int>(length);
    cout << avg << "\n";
}

int main() {
    vector arr1{1,2,3};
    avg(arr1);

    vector arr2{2.4,5.6,7.8};
    avg(arr2);
    return 0;
}
#+end_src

#+RESULTS:
: 2
: 5.26667

#+begin_src cpp :results output
#include <iostream>
#include <vector>
#include <cstddef>
using namespace std;
template <typename T>

T print(vector<T>& arr) {
    size_t length {arr.size()};

}

T getnumber() {
    int n{};
    do {
        cout << "Enter a number blw 1 to 9" << "\n";
        cin >> n;
    }while(n < 1 || n > 9);

    return
}

int main() {

    vector arr{1,6,4,6,3,3,8};
    return 0;
}
#+end_src

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int arr[5] = {2,2,3,4,5};
    int n;
    cin >> n;
    //int found = 0;
    for(int i=0;i<5;i++) {
        if(arr[i] == n){
            cout << i << "\n";
            //found = 1;
            return 0;
        }
    }
    // if(!found) {
    //     cout << "Element not found" << "\n";
    // }
    cout << "Element not found";

    return 0;
}
#+end_src

#+begin_src cpp :results output
#include <iostream>
#include <vector>
#include <cstddef>
#include <limits>
using namespace std;

int fun(vector<int>& arr, int val) {
    for(size_t index = 0; index < arr.size();++index) {
        if(arr[index] == val) {
            return static_cast<int>(index);
            //return true;
        }
    }
    return -1;
}

int get() {
    int num;
    do{
        cout << "Enter a number between 1 to 9: " << "\n";
        cin >> num;

        if(!cin) {
            cin.clear();
        }
        cin.ignore(numeric_limits<streamsize>::max(), '\n');
    } while(num < 1 || num > 9);

    return num;
}

int main() {
    vector arr{1,2,7,3,5};
    int num {get()};
    int ans = fun(arr , num);
    if(ans != -1) {
        cout << "The index of the number " << num << " is: " << ans << '\n';
    }else {
        cout << "The number does not exist in the array" << "\n";
    }
    return 0;
}
#+end_src

Here we use cin.clear to start the broken input method, it checks if the input method is broken if it is then start it again.
And cin.ignore the dump what we dont want means it clear the clogged pipe of inputs and keeps only valid.
The '\n' is for the cin.ignore to know where it to stop.
** Range based for Loops
:PROPERTIES:
:ID:       5163ff1a-fc7a-471b-8a8b-6c0302b83ecb
:END:
#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector arr {1,2,3,4,5};
    for(int num:arr) {
        cout << num << " ";
    }
    return 0;
}
#+end_src

#+RESULTS:
: 1 2 3 4 5

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector arr {1,2,3,44,4};
    for(auto num : arr) {
        cout << num << " ";
    }
    return 0;
}
#+end_src

#+RESULTS:
: 1 2 3 44 4

Avoid this for strings. use reference

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector arr {"Spiderman","No", "way", "Home"};
    for(auto& word : arr ) {
        //word = "Blank";  we can also change the values from here since it is reference
        cout << word << " ";
    }


    return 0;
}
#+end_src

#+RESULTS:
: Blank Blank Blank Blank

*For range based for loops, prefer to define the elements type as*
- auto        - when u want to modify copies of elements
- auto&       - when u want to modify original elements.
- const auto& - when u only want to view elements.
** Using unscoped emumerators for indexing
:PROPERTIES:
:ID:       d04bbae6-231f-41bf-919d-679f21adec80
:END:

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

namespace Names {
    enum Name {Shiva,prasad,sunny,venkatesh};
}

int main() {
    vector marks {10,90,78,89};
    marks[Names::prasad] = 100;
    for(int mark : marks) {
        cout << mark << " ";
    }
    return 0;
}
#+end_src

#+RESULTS:
: 10 100 78 89
** resizing std::vector at runtime
:PROPERTIES:
:ID:       fa55b4c5-d6fb-44df-9322-ec6c3184734c
:END:

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector a{1,2,4};
    cout << a.size() << "\n";
    a.resize(5);

    for(auto i : a) {
        cout << i << " ";
    }
    cout << "\n";
    cout << a.size();
    return 0;
}
#+end_src

#+RESULTS:
: 3
: 1 2 4 0 0
: 5

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector a{1,2,3,4,5};
    cout << a.size() << "\n";

    for(auto i : a) {
        cout << i << " ";
    }
    cout << "\n";
    a.resize(3);
    cout << a.size() << "\n";

    for(auto i : a) {
        cout << i << " ";
    }
    return 0;
}
#+end_src

#+RESULTS:
: 5
: 1 2 3 4 5
: 3
: 1 2 3

*Reallocation Process*
- std::vector acquires new memory with capacity for the desired number of elements. These elements are value-initialized.
- The elements in the old memory are copied (or moved, if possible) into the new memory. The old memory is then returned to the system.
- The capacity and length of the std::vector are set to the new values.

*** length and capacity
:PROPERTIES:
:ID:       ff769aa6-347e-4b18-bb40-058a22fa0a6b
:END:
#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

void print(vector<int>& a){
    cout << "Length: " << a.size() << " Capacity: " << a.capacity() << "\n";
}

int main() {
    vector a{1,2,3,4,5};

    print(a);
    for(auto i:a) {
        cout << i << " ";
    }
    cout << "\n";

    a.resize(3);
    print(a);
    for(auto i:a) {
        cout << i << " ";
    }
    cout << "\n";

    a.resize(5);
    print(a);
    for(auto i:a) {
        cout << i << " ";
    }
    return 0;
}
#+end_src

#+RESULTS:
: Length: 5 Capacity: 5
: 1 2 3 4 5
: Length: 3 Capacity: 5
: 1 2 3
: Length: 5 Capacity: 5
: 1 2 3 0 0

When we initialized our vector with 5 elements, the capacity was set to 5, indicating that our vector initially allocated space for 5 elements. The length was also set to 5, indicating that all of those elements are in use.

After we called v.resize(3), the length was changed to 3 to fulfill our request for a smaller array. However, note that the capacity is still 5, meaning that the vector did not do a reallocation!

Finally, we called v.resize(5). Because the vector already had a capacity of 5, it did not need to reallocate. It simply changed the length back to 5, and value-initialized the last two elements.

*** shrink_to_fit
:PROPERTIES:
:ID:       116dd243-8ec6-4aa3-8a5b-05e613df75af
:END:
#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;
void print(vector<int>& a) {
    cout << "Length: " << a.size() << " Capacity: " << a.capacity() << "\n";
}
int main() {
    vector arr{1,2,3,4,5,6};
    print(arr);
    for(auto i : arr) {
        cout << i << " ";
    }
    cout << "\n";

    arr.resize(3);
    print(arr);
    for(auto i : arr) {
        cout << i << " ";
    }
    cout << '\n';

    arr.shrink_to_fit();
    print(arr);
    for(auto i : arr) {
        cout << i << " ";
    }

    return 0;
}
#+end_src

#+RESULTS:
: Length: 6 Capacity: 6
: 1 2 3 4 5 6
: Length: 3 Capacity: 6
: 1 2 3
: Length: 3 Capacity: 3
: 1 2 3
** std::vector and stack behaviour
:PROPERTIES:
:ID:       acd90f7a-3082-4250-ba52-ccc7650fc428
:END:
In programming, a stack is a container data type where the insertion and removal of elements occurs in a LIFO(last in first out) manner. This is commonly implemented via two operations named push and pop:

| Push        | puts new element on top of stack     |                                    |
| Pop         | remove the top element from top      | may return removed element or void |
| Top or Peek | get the top element of the stack     | do not remove item                 |
| Emptying    | Determine if stack has no elements   |                                    |
| Size        | count how many elememts in the stack |                                    |

stack behaviour with std::vector

| push_back()    | put new element on top of stack             | Add elements to end of vector                     |
| pop_back()     | Remove element from the stack               | Returns void,removes element at the end of vector |
| back()         | get the top element on the stack            | does not remove item                              |
| emplace_back() | Alternate form of push_back() more effcient | Add elememts to the vector                        |

#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

void print(vector<int>& stack) {
    if(stack.empty()) {
        cout << "Empty" << '\n';
    }

    for(auto i : stack) {
        cout << i << ' ';
    }
    cout << '\n';

   cout << "Length: " << stack.size() << " capacity: " << stack.capacity() << '\n';
}

int main() {
    vector<int> stack{};
    print(stack);

    stack.push_back(1);
    print(stack);

    stack.push_back(2);
    print(stack);
    return 0;
}
#+end_src

#+RESULTS:
: Empty
:
: Length: 0 capacity: 0
: 1
: Length: 1 capacity: 1
: 1 2
: Length: 2 capacity: 2
** reserve member function
:PROPERTIES:
:ID:       619c0814-e97c-4b1d-9bcf-85d9f2f8430a
:END:
#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

void print(vector<int>& a) {
    if(a.empty()) {
        cout << "Empty" << '\n';
    }
    for(auto i : a) {
        cout << i << ' ';
    }
    cout << '\n';
    cout << "Length: " << a.size() << " Capacity: " << a.capacity() << '\n';
}

int main() {
    vector<int> stack{};

    print(stack);

    stack.reserve(6);
    print(stack);

    stack.push_back(1);
    print(stack);

    stack.push_back(2);
    print(stack);
    return 0;
}
#+end_src

#+RESULTS:
#+begin_example
Empty

Length: 0 Capacity: 0
Empty

Length: 0 Capacity: 6
1
Length: 1 Capacity: 6
1 2
Length: 2 Capacity: 6
#+end_example

#+begin_src cpp :results output
#include <iostream>
#include <vector>
#include <limits>
using namespace std;

int main() {
    vector<int> a{};

    while(true) {
        cout << "Enter the digits or -1 to finish: "  << '\n';
        int x{};
        cin >> x;

        if(!cin) {
            cin.clear();
            cin.ignore(numeric_limits<streamsize>::max(),'\n');
        }
        if(x == -1) {
            break;
        }

        a.push_back(x);
    }

    for(auto i:a) {
        cout << i << ' ';
    }

    return 0;
}
#+end_src
** std::vector<bool>
:PROPERTIES:
:ID:       777c7d81-b2e4-446f-9dea-151450a23115
:END:
#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

int main() {
    vector<bool> B{true,false,false};
    for(auto i : B) {
        cout << i << ' ';
    }
    cout << '\n';
    B[2] = true;
    for(auto i : B) {
        cout << i << ' ';
    }
    return 0;
}
#+end_src

#+RESULTS:
: 1 0 0
: 1 0 1
First, std::vector<bool> has a fairly high amount of overhead (sizeof(std::vector<bool>) is 40 bytes on the author’s machine), so you won’t save memory unless you’re allocating more Boolean values than the overhead for your architecture.

Second, the performance of std::vector<bool> is highly dependent upon the implementation (as implementations aren’t even required to do optimization, let alone do it well). Per this article, a highly optimized implementation can be significantly faster than alternatives. However, a poorly optimized implementation will be slower.

Third and most importantly, std::vector<bool> is not a vector (it is not required to be contiguous in memory), nor does it hold bool values (it holds a collection of bits), nor does it meet C++’s definition of a container.
** Quiz questions
#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

enum Game {health_portions,torches,arrows};

int print(const vector<int>& a) {
    int sum = 0;
    for(auto i:a) {
        sum += i;
    }
    return sum;
}

int main() {
    vector<int> bag{1,5,10};
    cout << "You have total " << print(bag) << " items" << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: You have total 16 items

#+begin_src cpp :results output
#include <iostream>
#include <vector>
#include <string_view>
using namespace std;

enum Game {health_portions,torches,arrows};

string_view enumtostring(Game ref) {
    switch(ref) {
        case health_portions : return "health portions";
        case  torches : return "torches";
        case arrows : return "arrows";
        default: return "Error";
    }
}

void print(vector<int>& a) {
   for(int i=0;i<3;i++) {
       cout << "You have " << a[i] << ' ' << enumtostring(static_cast<Game>(i)) << '\n';
   }
}

int total(vector<int>& a) {
    int sum = 0;
    for(auto i : a) {
        sum += i;
    }
    return sum;
}

int main() {
    vector<int> inventory{1,5,10};
    print(inventory);
    cout << "You have total " << total(inventory) << " items" << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: You have 1 health portions
: You have 5 torches
: You have 10 arrows
: You have total 16 items


#+begin_src cpp :results output
#include <iostream>
#include <vector>
using namespace std;

void max(const vector<int>& a) {
    int max = a[0];
    int maxindex;
    size_t length = a.size();
    for(size_t index = 0;index < length;index++) {
        if(a[index] > max) {
            max = a[index];
            maxindex = static_cast<int>(index);
        }
    }
    cout << "Max element has index " << maxindex << " and value " << max << '\n';
}

void min(const vector<int>& a) {
    int min = a[0];
    int minindex;
    size_t length = a.size();
    for(size_t index = 1;index < length; index++) {
        if(a[index] < min) {
            min = a[index];
            minindex = static_cast<int>(index);
        }
    }

    cout << "Min element has index "  << minindex << " and value " << min << '\n';
}

int main() {
    vector<int> a{3,8,2,5,7,8,2};
    min(a);
    max(a);
    return 0;
}
#+end_src
** std::arrays
:PROPERTIES:
:ID:       6c8378ea-04df-4bab-9c0d-18455ecef5d5
:END:

#+begin_src cpp :results output
#include <iostream>
#include <array>
using namespace std;

int main() {
    array<int, 5> a{};
    cout << a[0] << '\n';

    constexpr int len{8};
    array<int, len> b{};
    cout << b[1] << '\n';

    enum Colors {
        white,
        green,
        blue,
        black
    };

    array<int, black> c{};
    cout << b[10] << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: 0
: 0
: -1098323968

*Defining your std::array as constexpr whenever possible. if Your std::array is not a constexpr, consider using std::vector instead*

#+begin_src cpp :results output
#include <iostream>
#include <array>
using namespace std;

int main() {
    array a1 {1,2,3,4};
    cout << a1[0];
    return 0;
}
#+end_src
* Iterators
:PROPERTIES:
:ID:       fc016b77-388b-4db4-aa48-963fab54dbe7
:END:

#+begin_src cpp :results output
#include <iostream>
#include <array>
using namespace std;

int main() {
    array a{0,1,2,3,5,5};

    auto begin{&a[0]};
    auto end{begin + size(a)};

    for(auto ptr{begin};ptr != end;++ptr) {
        cout << *ptr << ' ';
    }
    return 0;
}
#+end_src

#+RESULTS:
: 0 1 2 3 5 5


#+begin_src cpp :results output
#include <iostream>
#include <array>
using namespace std;

int main() {
    array a{0,1,2,3,4,5};

    auto begin{a.begin()};
    auto end{a.end()};

    for(auto ptr{begin}; ptr != end;++ptr) {
        cout << *ptr << ' ';
    }
    return 0;
}
#+end_src

#+RESULTS:
: 0 1 2 3 4 5
* Introduction to standard library algorithms
:PROPERTIES:
:ID:       59f9f174-a742-40b6-b2b1-27a4126a62ca
:END:
** std::find - find an element by value
:PROPERTIES:
:ID:       6f68aaaa-7763-4787-8313-d0c6d010b5bf
:END:
std::find searches for a first occurence of an element in a container.
 takes 3 parameters: an iterator to the starting element in the sequence, an iterator to the ending element in the sequence, and a value to search for. It returns an iterator pointing to the element (if it is found) or the end of the container (if the element is not found).

 #+begin_src cpp :results output
#include <iostream>
#include <array>
#include <algorithm>
using namespace std;

int main() {
    array a{1,2,3,4,5,6};
    int ele{5};
    auto found{find(a.begin(), a.end(), ele)};
    if(found == a.end()) {
        cout << "element not found";
    }else {
        cout << *found << '\n';
    }
    return 0;
}
#+end_src

#+RESULTS:
: 5

 iterators use or mimics the syntax of pointers to replace or see the value of element. But they are not actually pointers.
** std::find_if - find an element that matches some condition
:PROPERTIES:
:ID:       5bf53b47-95b3-45ef-a648-43a6cbe66741
:END:
#+begin_src cpp :results output
#include <iostream>
#include <array>
#include <string_view>
#include <algorithm>
using namespace std;

bool contains(string_view str) {
    return str.find("sad") != string_view::npos;
}

int main() {
    array<string_view, 4> a{"shiva", "prasad", "kyaram", "sunny"};

    auto found {find_if(a.begin(), a.end(), contains)};

    if(found == a.end()) {
        cout << "Not found" << '\n';
    }else {
        cout << *found << '\n';
    }

    return 0;
}
#+end_src

#+RESULTS:
: prasad
** std::count and std::count_if to count how many occurences there are
:PROPERTIES:
:ID:       9881d197-962f-44f6-84e7-fbfce39261ea
:END:
#+begin_src cpp :results output
#include <iostream>
#include <string_view>
#include <algorithm>
#include <array>
using namespace std;

bool containsnut(string_view str) {
    return str.find("nut") != string_view::npos;
}

int main() {
    array<string_view, 5> a{"apple", "walnut", "peanut", "banana", "nut"};

    auto nuts {count_if(a.begin(), a.end(), containsnut)};

    cout << nuts << '\n';

    return 0;
}
#+end_src
** std::sort
:PROPERTIES:
:ID:       7aaac077-a32d-49f2-9b79-d0576f2b72d3
:END:
#+begin_src cpp :results output
#include <iostream>
#include <array>
#include <algorithm>
using namespace std;
bool greatest(int a, int b) {
    return (a>b);
}

int main() {
    array arr{1,7,4,6,2,6};
    sort(arr.begin(), arr.end(), greatest);
    for(int i : arr) {
        cout << i << ' ';
    }
    cout << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 7 6 6 4 2 1

#+begin_src cpp :results output
#include <iostream>
#include <array>
#include <algorithm>
using namespace std;
// bool greatest(int a, int b) {
//     return (a<b);
// }

int main() {
    array arr{1,7,4,6,2,6};
    sort(arr.begin(), arr.end());
    for(int i : arr) {
        cout << i << ' ';
    }
    cout << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 1 2 4 6 6 7
** std::for_each
:PROPERTIES:
:ID:       7613e555-a24d-45dd-ac8b-deb1b90c4baa
:END:

#+begin_src cpp :results output
#include <iostream>
#include <array>
#include <algorithm>
using namespace std;

void dou(int& i) {
    i = i*2;
}

int main() {
    array a{1,2,3,4};
    for_each(a.begin(), a.end(), dou);

    for(auto i : a) {
        cout << i << ' ';
    }
    cout << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 2 4 6 8

#+begin_src cpp :results output
#include <iostream>
#include <array>
#include <chrono> // for std::chrono functions

using namespace std;
class Timer
{
private:
	// Type aliases to make accessing nested type easier
	using Clock = std::chrono::steady_clock;
	using Second = std::chrono::duration<double, std::ratio<1> >;

	std::chrono::time_point<Clock> m_beg { Clock::now() };

public:
	void reset()
	{
		m_beg = Clock::now();
	}

	double elapsed() const
	{
		return std::chrono::duration_cast<Second>(Clock::now() - m_beg).count();
	}
};

int main() {
    array a{12,3,4,5,6};
    Timer t;
    for(auto i : a) {
        cout << i << ' ';
    }
    cout << t.elapsed() << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 12 3 4 5 6 3.8302e-05
* Dynamic memory allocation with new and delete
:PROPERTIES:
:ID:       6f15ad86-34ed-425d-9874-eb215890c8c3
:END:
** new
:PROPERTIES:
:ID:       0050abd5-f638-44ee-8dba-d86cd4d69ec7
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    new int a;
    return 0;
}
#+end_src

In the above case, we’re requesting an integer’s worth of memory from the operating system. The new operator creates the object using that memory, and then returns a pointer containing the address of the memory that has been allocated.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int* ptr = new int;
    cout << *ptr << '\n';

    *ptr = 44;
    cout << *ptr << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: 0
: 44

Note that accessing *heap-allocated* objects is generally slower than accessing stack-allocated objects. Because the compiler knows the address of stack-allocated objects, it can go directly to that address to get a value. Heap allocated objects are typically accessed via pointer. This requires two steps: *one to get the address of the object (from the pointer), and another to get the value.*

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int* ptr{new int {9}};
    int* ptr1{new int {1}};
    cout << *ptr << '\n';
    cout << *ptr1 << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 9
: 1
** delete
:PROPERTIES:
:ID:       d8ffafdf-aec0-4124-8736-c7975a1e5a0b
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int* ptr {new int (9)};
    delete ptr;
    ptr = NULL;
    cout << *ptr << '\n';
    return 0;
}
#+end_src

#+RESULTS:

The delete operator does not actually delete anything. It simply returns the memory being pointed to back to the operating system. The operating system is then free to reassign that memory to another application (or to this application again later).

Although the syntax makes it look like we’re deleting a variable, this is not the case! The pointer variable still has the same scope as before, and can be assigned a new value (e.g. nullptr) just like any other variable.

Note that deleting a pointer that is not pointing to dynamically allocated memory may cause bad things to happen.

#+begin_src cpp :results output
int* value { new (std::nothrow) int{} }; // ask for an integer's worth of memory
if (!value) // handle case where new returned null
{
    // Do error handling here
    std::cerr << "Could not allocate memory\n";
}
#+end_src


memory leak
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    {
        int* ptr{new int (5)};  //dynamically allocated int specific block
    }
    // ptr has been destroyed after the above block
    // but we never deallocated the memory so the os can now either access it or delete so it just becomes useless now;

    return 0;
}
#+end_src
* Dynamically allocating arrays
:PROPERTIES:
:ID:       f5882cae-641c-4957-9ccb-3f4e924f0190
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    int length{3};
    int* ptr{new int[length]{}};
    ptr[0] = 1;
    cout << ptr[0];
    delete[] ptr;
    return 0;
}
#+end_src

#+RESULTS:
: 1

#+begin_src cpp :results output
#include <iostream>
using namespace std;

int main() {
    size_t len=5;
    int* array {new int[len]{1,2,3,4,5}};
    cout << array[3];
    return 0;
}
#+end_src

#+RESULTS:
: 4


#+begin_src cpp :results output
#include <iostream>
#include <algorithm>
#include <string_view>
using namespace std;

// bool small(string_view a, string_view b) {
//     return (a<b);
// }

int main() {
    size_t len;
    cout << "Enter the no of Names: " << '\n';
    cin >> len;
    auto *arr{new string[len]{}};
    for(size_t i = 0;i<len;i++) {
        getline(cin>>ws, arr[i]);
    }

    sort(arr, arr + len);

    for(size_t i= 0;i<len;i++){
        cout << arr[i] << '\n';
    }

    delete[] arr;

    return 0;
}
#+end_src

#+RESULTS:
: Enter the no of Names:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Color{
public:
    enum color {
        a,
        b,
        c,
        e,
        f
    };
};

int main() {
    Color::color o{};
    cout << o;
    cout << sizeof(o);
    return 0;
}
#+end_src

#+RESULTS:
:
* Destructor indetail
:PROPERTIES:
:ID:       0334ee2b-b51a-451d-b97b-643aa09581d4
:END:
A destructor is another special kind of class member function that is executed when an object of that class is destroyed. Whereas constructors are designed to initialize a class, destructors are designed to help clean up.

When an object goes out of scope normally, or a dynamically allocated object is explicitly deleted using the delete keyword, the class destructor is automatically called (if it exists) to do any necessary clean up before the object is removed from memory. For simple classes (those that just initialize the values of normal member variables), a destructor is not needed because C++ will automatically clean up the memory for you.

However, if your class object is holding any resources (e.g. dynamic memory, or a file or database handle), or if you need to do any kind of maintenance before the object is destroyed, the destructor is the perfect place to do so, as it is typically the last thing to happen before the object is destroyed.

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Array{
    int* m_ar{};
    int m_length{};
public:
    Array(int length){
        m_ar = new int[static_cast<size_t>(length)]{};
        m_length = length;
    }
    ~Array() {
        delete[] m_ar;
    }

    void setValue(int index,int value) {
        m_ar[index] = value;
    }

    int getValue(int index) {
        return m_ar[index];
    }

    int getLength() {
        return m_length;
    }
};

int main() {
    Array ar(10);
    for(int i =0;i < ar.getLength(); i++) {
        ar.setValue(i,i+1);
    }
    cout << ar.getValue(2);
    return 0;
} //ar is destroyed here
#+end_src

#+RESULTS:
: 3

* RAII[[https://share.gemini.google/3gFhyGLcNj3P][ link]]
:Properties:
:ID:       920749bb-f11d-45db-89ce-329a6e7bb708
:END:
* Introduction to Lamdas (anonymous functions)

Syntax of Lamda function

[ captureClause ] ( parameters ) -> returnType
{
        statements;
}

Normal Function
#+begin_src cpp :results output
bool greater(int a, int b) {
    return a > b;
}
#+end_src

Lamda function
#+begin_src cpp :results output
auto is_greater = [](int a,int b)
    {return a > b;};
#+end_src

#+begin_src cpp :results output
#include <iostream>
#include <algorithm>
#include <vector>
using namespace std;

int main() {
    vector<int> arr{1,2,3,4,5,6};
    int limit = 3;

    int count = count_if(arr.begin(), arr.end(), [limit](int n) {return n > limit;});

    cout << count;

    return 0;
}
#+end_src

#+RESULTS:
: 3

#+begin_src cpp :results output
#include <algorithm>
#include <array>
#include <iostream>
#include <string_view>

int main()
{
  constexpr std::array<std::string_view, 4> arr{ "apple", "banana", "walnut", "lemon" };

  // Define the function right where we use it.
  auto found{ std::find_if(arr.begin(), arr.end(),
                           [](std::string_view str) // here's our lambda, no capture clause
                           {
                             return str.find("nut") != std::string_view::npos;
                           }) };

  if (found == arr.end())
  {
    std::cout << "No nuts\n";
  }
  else
  {
    std::cout << "Found " << *found << '\n';
  }

  return 0;
}
#+end_src

#+RESULTS:
: Found walnut

we can store lamda in a named variable and pass it to a function.
#+begin_src cpp :results output
auto isEven{
    [](int i)
    {
        return (i % 2) == 0;
    }
};

return std::all_of(array.begin(),array.end(),isEven);
#+end_src


Storing a lamda for post-defination

#+begin_src cpp :results output
#include <iostream>
#include <functional>
using namespace std;

int main() {
    //using functional pointer
    double (*addnumbers1)(double, double) {
        [](double a,double b) {
            return a+b;
        }
    };

    cout << addnumbers1(1,2) << '\n';

    //using std::function
    function addnumbers2{
        [](double a, double b) {
            return a + b;
        }
    };

    cout << addnumbers2(5,6) << '\n';

    //using auto
    auto addnumbers3 {
        [](double a, double b) {
            return a + b;
        }
    };

    cout << addnumbers3(1,6) << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: 3
: 11
: 7

passing lamda to a function
example of passing  a function as parameter to another function
#+begin_src cpp :results output
#include <iostream>
using namespace std;

int add(int a, int b) { return a + b; }
int mul(int a, int b) { return a * b; }

int apply(int x, int y, int (*op)(int, int)) {
    return op(x, y);
}

int main() {
    cout << apply(3, 4, add) << "\n";  // 7
    cout << apply(3, 4, mul) << "\n";  // 12
}
#+end_src

now using lamda
#+begin_src cpp :results output
#include <iostream>
#include <functional>
using namespace std;
//using std::function parameter
void repeat(int n, const function<void(int)>& fn) {
    for(int i = 0; i < n;i++) {
        fn(i);
    }
}

//using template
template <typename T>
void repeat2(int n, const T& fn) {
    for(int i = 0; i < n ; i++){
        fn(i);
    }
}

int main() {

    auto lamda{
        [](int i) {
            cout << i << ' ';
        }
    };

    repeat(3,lamda);
    repeat2(3,lamda);

    return 0;
}
#+end_src

#+RESULTS:
: 0 1 2 0 1 2

#+begin_src cpp :results output
#include <iostream>
using namespace std;

void repeat(int n, print()) {
    for(int i =0; i < n; i++){
        print(i);
    }
}

int print(int i) {
    cout << i;
}

int main() {

    return 0;
}
#+end_src

#+RESULTS:

** Generic Lamdas
:PROPERTIES:
:ID:       3a220f14-100f-4143-bc5e-950a3dac20ca
:END:
Lamdas woth one or more auto type parameters which works with wide variety of types are called generic lamdas

The std::adjacent_find function in C++ searches a range [first, last) for the first pair of consecutive elements that are equal (or satisfy a given binary predicate), returning an iterator to the first element of that pair.  If no such pair is found, it returns the last iterator.

Syntax and Parameters
Defined in the <algorithm> header, the function has two primary overloads:

Equality Check: std::adjacent_find(first, last) compares elements using operator==.
Predicate Check: std::adjacent_find(first, last, pred) uses a binary predicate pred to determine if two elements match.

#+begin_src cpp :results output
#include <iostream>
#include <array>
#include <algorithm>
#include <string_view>
using namespace std;

int main() {
    constexpr array month {
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    };

     const auto sameletter{adjacent_find(month.begin(), month.end(),
                                         [](const auto& a,const auto& b){
                                             return (a[0] == b[0]);
    })};
    if(sameletter != month.end()) {
        cout << *sameletter << " and " << *next(sameletter) << " are equal";
    }

    return 0;
}
#+end_src

#+RESULTS:
: June and July are equal

#+begin_src cpp :results output
#include <iostream>
#include <array>
#include <algorithm>
#include <string_view>
using namespace std;

int main() {
    constexpr array month {
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    };

    auto fiveletter{
        count_if(month.begin(), month.end(),
            [](std::string_view str) {
            return (str.length() == 5);
            })};

    cout << fiveletter << '\n';
}

#+end_src
* Operator overloading.
:PROPERTIES:
:ID:       915aaad2-5f5b-4901-ab87-7b352302d36b
:END:
using function overloading to overload operators is called operator overloading.i

First, almost any existing operator in C++ can be overloaded. The exceptions are: conditional (?:), sizeof, scope (::), member selector (.), pointer member selector (.*), typeid, and the casting operators.

Second, you can only overload the operators that exist. You can not create new operators or rename existing operators. For example, you could not create an operator** to do exponents.

Third, at least one of the operands in an overloaded operator must be a user-defined type. This means you could overload operator+(int, Mystring), but not operator+(int, double).

*Ways to overload operator*
1. the member function way
2. friend function way
3. normal way

** opearator overloading using friend function*
#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Cents{
    int m_cents{};
public:
    Cents(int cents) : m_cents {cents} {}

    friend Cents operator+(Cents& c1, Cents& c2);

    int getCents() {
       return m_cents;
    }
};

Cents operator+(Cents& c1, Cents& c2) {
    return c1.m_cents + c2.m_cents;
}


int main() {
    Cents a{1};
    Cents b{2};
    cout << a.getCents() << '\n';
    Cents sum{a + b};
    cout  << sum.getCents() << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 1
: 3

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Cents{
    int m_cents{};
public:
    Cents(int cents) : m_cents{cents} {}

    friend Cents operator-(Cents& c1, Cents& c2);

    int getCents() {
        return m_cents;
    }
};

Cents operator-(Cents& c1, Cents& c2) {
    return c1.m_cents - c2.m_cents;
}

int main() {
    Cents a{2};
    Cents b{3};
    cout << b.getCents() << '\n';
    Cents minus{a- b};
    cout << minus.getCents() << '\n';
    return 0;
}
#+end_src

#+RESULTS:
: 3
: -1

with different type
Cents, int

For adding different types we need to write two oveloading functions one for  x + cents(4) and cents(4) + x because these are treated as diff rather than one like in same type.

#+begin_src cpp :results output
#include <iostream>
using namespace std;
class Cents{
    int m_cents{};
public:
    Cents(int cents) : m_cents {cents} {}

    friend Cents operator+(Cents& c, int x);

    friend Cents operator+(int x, Cents& c);

    int getCents() {
        return m_cents;
    }
};

Cents operator+(Cents& c, int x) {
    return c.m_cents + x;
}

Cents operator+(int x, Cents& c) {
    return c.m_cents + x;
}

int main() {
    Cents a{3};
    Cents sum=a+4;
    cout << sum.getCents();
    return 0;
}
#+end_src

#+RESULTS:
: 7
** overloading operator using normal functions

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Cents{
    int m_cents{};
public:
    Cents(int cents) : m_cents{cents} {}

    int getCents() {
        return m_cents;
    }
};

Cents operator+(Cents& c1, Cents& c2) {
    return (c1.getCents() + c2.getCents());
}

int main() {
    Cents a{2};
    Cents b{3};
    Cents sum{a + b};
    cout << sum.getCents();
    return 0;
}
#+end_src

#+RESULTS:
: 5
** overloading I/O operators
overloading >> operator
#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Cents{
    int m_cents{};
    string m_country{};
public:
    Cents(int cents, string country) : m_cents {cents}, m_country {country} {};

    friend ostream& operator<<(ostream& out, Cents& c);

    int getCents() {
        return m_cents;
    }
};

ostream& operator<<(ostream& out, Cents& c) {
    out << c.m_cents << ' '  << c.m_country;
    return out;
}

int main() {
    Cents a{20, "India"};
    cout << a;
    return 0;
}
#+end_src

#+RESULTS:
: 20 India

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Point{
    int m_x{};
    int m_y{};
    int m_z{};
public:
    Point(int x= 0, int y=0 , int z=0) : m_x {x}, m_y{y} , m_z{z} {};

    friend ostream& operator<<(ostream& out, Point& p);
    friend istream& operator>>(istream& out, Point& p);
};

ostream& operator<<(ostream& out, Point& p) {
    out << "( " << p.m_x << ", " << p.m_y << ", " << p.m_z << " )";
    return out;
}

istream& operator>>(istream& in, Point& p) {
    in >> p.m_x >> p.m_y >> p.m_z;
    return in;
}

int main() {
    Point p;
    cin >> p;
    cout << p;
    return 0;
}
#+end_src
** overloading operators using member function

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Cents{
    int m_cents{};
public:
    Cents(int cents) : m_cents{cents} {}

    int getCents() {
        return m_cents;
    }
};

Cents Cents::operator+(int value) {
    return Cents {m_cents + value};
}

int main() {

    Cents c1{1};
    Cents c2{c1 + 1};
    cout << c2.getCents();

    return 0;
}
#+end_src

#+RESULTS:
** overloading unary operators +,-,!
:PROPERTIES:
:ID:       4d8d3871-d0a6-49bf-8b5d-95e4c9d58456
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Cents{
    int  m_cents{};
public:
    Cents(int cents) : m_cents{cents}{}
    Cents operator-();

    int getCents() {
        return m_cents;
    }
};

Cents Cents::operator-() {
    return -m_cents;
}

int main() {
    Cents c{2};
    cout << -c.getCents();
    return 0;
}
#+end_src

#+RESULTS:
: -2
** overloading comparison operators
:PROPERTIES:
:ID:       855d9394-e7b4-475d-90fb-2dea5bae927c
:END:
#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Car{
    string m_make{};
    string m_model{};
public:
    Car(string make, string model) : m_make {make} , m_model {model} {}

    friend bool operator==(Car& c1, Car& c2);
    friend bool operator!=(Car& c1, Car& c2);
};

bool operator==(Car& c1, Car& c2) {
    return (c1.m_make == c2.m_make && c1.m_model == c2.m_model);
}

bool operator!=(Car& c1, Car& c2) {
    return (c1.m_make != c2.m_make || c1.m_model != c2.m_model);
}

int main() {
    Car c1{"Toyota", "A"};
    Car c2("Toyota", "B");
    if(c1 == c2) {
        cout << "Equal" << '\n';
    }else {
        cout << "Not equal" << '\n';
    }
    return 0;
}
#+end_src

#+RESULTS:
: Not equal
** overloading operator[]
 #+begin_src cpp :results output
#include <iostream>

class IntList
{
private:
    int m_list[10]{};

public:
    int& operator[] (int index)
    {
        return m_list[index];
    }
};

/*
// Can also be implemented outside the class definition
int& IntList::operator[] (int index)
{
    return m_list[index];
}
,*/

int main()
{
    IntList list{};
    list[2] = 3; // set a value
    std::cout << list[2] << '\n'; // get a value

    return 0;
}

#+end_src

#+RESULTS:
: 3
** shallow vs deep copying
:PROPERTIES:
:ID:       ad1e3bc7-0c20-4573-9ccf-c74e37d35e0b
:END:
#+begin_src cpp :results output
#include <cassert>
#include <iostream>

class Fraction
{
private:
    int m_numerator { 0 };
    int m_denominator { 1 };

public:
    // Default constructor
    Fraction(int numerator = 0, int denominator = 1)
        : m_numerator{ numerator }
        , m_denominator{ denominator }
    {
        assert(denominator != 0);
    }

    // Possible implementation of implicit copy constructor
    Fraction(const Fraction& f)
        : m_numerator{ f.m_numerator }
        , m_denominator{ f.m_denominator }
    {
    }

    // Possible implementation of implicit assignment operator
    Fraction& operator= (const Fraction& fraction)
    {
        // self-assignment guard
        if (this == &fraction)
            return *this;

        // do the copy
        m_numerator = fraction.m_numerator;
        m_denominator = fraction.m_denominator;

        // return the existing object so we can chain this operator
        return *this;
    }

    friend std::ostream& operator<<(std::ostream& out, const Fraction& f1)
    {
     out << f1.m_numerator << '/' << f1.m_denominator;
     return out;
    }
};

#+end_src


#+begin_src cpp :results output
#include <iostream>
using namespace std;

class Something{
public:
    int* m_data;
    Something(int data) {
        m_data = new int(data);
    }
    ~Something() {
        delete m_data;
    }
};

int main() {
    Something S{20};
    Something R = S;
    cout << *R.m_data << '\n';
    return 0;
}
#+end_src
* Smart pointers
:PROPERTIES:
:ID:       c95f0d72-fbcf-4fd7-ac81-816f18704072
:END:

#+begin_src cpp :results output
#include <iostream>
using namespace std;

template <typename T>
class Auto_ptr{
    T* m_ptr;
public:
    Auto_ptr(T* ptr= nullptr) : m_ptr{ptr} {}

    ~Auto_ptr() { delete m_ptr; }

    T& operator*() const {return *m_ptr;}  // returns the actual resource object
    T* operator->() const {return m_ptr;}  // returns raw pointer m_ptr
};

class Resource{
    string m_name{};
    int m_data{};
public:
    Resource(string name, int data) : m_name{name} , m_data {data} {cout << "constructor ran\n";}
    ~Resource() {{cout << "Destructor ran\n";}}

    void print() {
        cout << m_name << " " << m_data << '\n';
    }
};

int main() {
    Auto_ptr<Resource> res = new Resource("Shiva", 20);
    res->print();
    return 0;
}
#+end_src

#+RESULTS:
: constructor ran
: Shiva 20
: Destructor ran

Exaplanation from claude
#+begin_src cpp :results output
#include <iostream>
#include <string>

template <typename T>
class Auto_ptr1
{
    T* m_ptr {};
public:
    Auto_ptr1(T* ptr = nullptr) : m_ptr(ptr) {}
    ~Auto_ptr1() { delete m_ptr; }

    T& operator*() const { return *m_ptr; }
    T* operator->() const { return m_ptr; }
};

class Resource
{
    std::string m_name;
    int m_health;
public:
    Resource(std::string name, int health)
        : m_name(name), m_health(health)
    {
        std::cout << m_name << " created with health " << m_health << "\n";
    }

    ~Resource() { std::cout << m_name << " destroyed\n"; }

    void takeDamage(int dmg) { m_health -= dmg; }
    void show() const { std::cout << m_name << " health: " << m_health << "\n"; }
};

int main()
{
    std::cout << "main starts\n";

    {   // inner scope
        Auto_ptr1<Resource> player(new Resource("Player", 100));

        player->show();        // calls m_ptr->show()
        player->takeDamage(30);
        player->show();
        (*player).show();      // same thing using operator*

        std::cout << "leaving inner scope\n";
    }   // player (the Auto_ptr1) dies here -> delete m_ptr -> Resource destructor runs

    std::cout << "back in main, player is gone\n";
}

#+end_src

** move semantics
:PROPERTIES:
:ID:       658c47e2-db18-42d7-b634-583276a5f4ea
:END:

What if, instead of having our copy constructor and assignment operator copy the pointer (“copy semantics”), we instead transfer/move ownership of the pointer from the source to the destination object? This is the core idea behind move semantics. Move semantics means the class will transfer ownership of the object rather than making a copy

#+begin_src cpp :results output
#include <iostream>
using namespace std;

template <typename T>
class Auto_ptr{
    T* m_ptr{};
public:
    Auto_ptr(T* ptr = nullptr) : m_ptr {ptr} {}

    ~Auto_ptr() {
        delete m_ptr;
    }

    Auto_ptr& operator=(Auto_ptr& a) {
        if(&a == this) {
            return *this;
        }
        delete m_ptr;
        m_ptr = a.m_ptr;
        a.m_ptr = nullptr;
        return *this;
    }

    T& operator*() {return *m_ptr;}
    T* operator->() {return m_ptr;}
};

class Resource{
    int m_data;
public:
    Resource(int data) : m_data {data} {cout << "Constrouctor ran\n";}
    void getData() {
        cout << m_data << '\n';
    }
    ~Resource() {cout << "Destrouctor ran\n";}
};

int main() {
    Auto_ptr<Resource> res1 = new Resource(10);
    Auto_ptr<Resource> res2;
    res2 = res1;
    res2->getData();
    return 0;
}
#+end_src

*rvalue reference* - the rvalue reference allows to capture temporary object in the move constructor and move its resources to another object.

** *move constructor* - Allows stealing resources from a temporary object and provide those resources to some other object.
:PROPERTIES:
:ID:       c71242cb-142c-4bda-a604-7be5dbd0a9a3
:END:

#+begin_src cpp :results output
#include <iostream>
#include <cstring>
using namespace std;

class String{
    char* m_data;
public:
    // Constructor
    String(const char* s)  {
        m_data = new char[strlen(s) + 1]; // + 1 for terminator
        strcpy(m_data, s);
        cout << "Constructed" << '\n';
    }

    //Copy construtor
    String(const String& other)  {
        m_data = new char[strlen(other.m_data) + 1];
        strcpy(m_data , other.m_data);
        cout << "copied" << '\n';
    }

    //Destructor
    ~String() {
        delete[] m_data;
        cout << "Destroyed" << '\n';
    }

    void print() {
        cout << m_data << '\n';
    }
};

int main() {
    String s1{"shiva"};
    String s2 = s1;
    s1.print();
    s2.print();
    return 0;
}
#+end_src

#+RESULTS:
: Constructed
: copied
: shiva
: shiva
: Destroyed
: Destroyed


In the above program we just copied one object data to another using copy constructor with this two strings will be created and memory is occupied by both.
Lets see how this is done by move constructor using rvalue references

#+begin_src cpp :results output
#include <iostream>
#include <cstring>
using namespace std;

class String{
    char* m_data{};
public:
    String(const char* s) {
        m_data = new char[strlen(s) + 1];
        strcpy(m_data, s);
        cout << "Constructed" << '\n';
    }

    //move constructor
    String(String&& other) {  // here we used && because in the main s1 is treated as temporary object which is rvalue
        m_data = other.m_data;  // here s1 and s2 are pointing to same data because of reference
        other.m_data = nullptr;  // set data of s1 to null
        cout << "Moved\n";
    }

    ~String() {
        delete[] m_data;
        cout << "Destroyed" << '\n';
    }

    void print() {
        if(m_data) {
            cout << m_data << "\n";
        }else{
            cout << "Empty" << '\n';
        }
    }
};

int main() {
    String s1{"shiva"};
    String s2 = move(s1);  // here s1 is treated as a temporary object
    s1.print();
    s2.print();
    return 0;
}
#+end_src
** move assignment
:PROPERTIES:
:ID:       4bcd91e9-615b-49ca-b8f1-9d5bfc0218f2
:END:

invoked when we overwrite data of a object that has already been created with another object

rough example for move constructor and move assignment

#+begin_src cpp :results output
#include <iostream>
using namespace std;

template <typename T>
class Auto_ptr{
    T* m_ptr{};
public:
    Auto_ptr(T* ptr = nullptr) : m_ptr {ptr} {}

    // move constructor
    Auto_ptr(Auto_ptr&& other) noexcept : m_ptr{other.m_ptr} {other.m_ptr = nullptr;}

    //move assignment
    Auto_ptr& operator=(Auto_ptr&& other) {
        if(&other == this) {
            return *this;
        }

        delete m_ptr;
        m_ptr = other.m_ptr;
        other.m_ptr = nullptr;
        return *this;
    }

    ~Auto_ptr() {
        delete m_ptr;
    }

    T& operator*() const {return *m_ptr;}
    T* operator->() const {return m_ptr;}
};

class Resource{
    int m_data{};
public:
    Resource(int data) : m_data{data} {cout << "Constructed\n";}

    int getData() {
        return m_data;
    }

    ~Resource() {cout << "Destructed\n";}
};

int main() {
    Auto_ptr<Resource> res1 = new Resource(5);
    Auto_ptr<Resource> res2 = new Resource(10);

    res2 = move(res1);
    cout << res2->getData() << '\n';

    return 0;
}
#+end_src

#+RESULTS:
: Constructed
: Constructed
: Destructed
: 5
: Destructed


#+begin_src cpp :results output
#include <iostream>

template<typename T>
class Auto_ptr4
{
	T* m_ptr {};
public:
    // Constructor
	Auto_ptr4(T* ptr = nullptr)
		: m_ptr { ptr }
	{
	}

    // Destructor
	~Auto_ptr4()
	{
		delete m_ptr;
	}

	// Copy constructor
	// Do deep copy of a.m_ptr to m_ptr
    // called when new object is created and immediately initialized it with existing object
	Auto_ptr4(const Auto_ptr4& a)
	{
		m_ptr = new T;
		,*m_ptr = *a.m_ptr;          // accessing atual object not memory address
	}

	// Move constructor
	// Transfer ownership of a.m_ptr to m_ptr
	Auto_ptr4(Auto_ptr4&& a) noexcept               // a promise to compiler that this fun will not generate error because it is just swapping memory address
		: m_ptr { a.m_ptr }                       // here two object ponting to same address
	{
		a.m_ptr = nullptr; // making it null because when fun is over its constructor is called and actual data is deleted. if we point it to null no actual will be deleted
	}

	// Copy assignment
	// Do deep copy of a.m_ptr to m_ptr
	Auto_ptr4& operator=(const Auto_ptr4& a)
	{
		// Self-assignment detection
		if (&a == this)          // if box1 = box2 then stop and return this
			return *this;

		// Release any resource we're holding
		delete m_ptr;              // it already has data if we dont delete it before overwriting memory leak will happen

		// Copy the resource
		m_ptr = new T;
		,*m_ptr = *a.m_ptr;

		return *this;
	}

	// Move assignment
	// Transfer ownership of a.m_ptr to m_ptr
	Auto_ptr4& operator=(Auto_ptr4&& a) noexcept
	{
		// Self-assignment detection
		if (&a == this)
			return *this;

		// Release any resource we're holding
		delete m_ptr;

		// Transfer ownership of a.m_ptr to m_ptr
		m_ptr = a.m_ptr;
		a.m_ptr = nullptr;

		return *this;
	}

	T& operator*() const { return *m_ptr; }
	T* operator->() const { return m_ptr; }
	bool isNull() const { return m_ptr == nullptr; }
};

class Resource
{
public:
	Resource() { std::cout << "Resource acquired\n"; }
	~Resource() { std::cout << "Resource destroyed\n"; }
};

Auto_ptr4<Resource> generateResource()
{
	Auto_ptr4<Resource> res{new Resource};
	return res; // this return value will invoke the move constructor
}

int main()
{
	Auto_ptr4<Resource> mainres;
	mainres = generateResource(); // this assignment will invoke the move assignment

	return 0;
}

#+end_src
** Types of smart pointer
:PROPERTIES:
:ID:       79435994-4ac4-44ac-aec6-b72b62ecc71a
:END:
 There are 4 smart pointer class
 1. std::auto_ptr
 2. std::unique_ptr
 3. std::shared_ptr
 4. std::weak_ptr

*** std::unique_ptr
:PROPERTIES:
:ID:       61653ce5-9738-45f5-b694-28c7fa6f5264
:END:

std::unique_ptr is the C++11 replacement for std::auto_ptr. It should be used to manage any dynamically allocated object that is not shared by multiple objects. That is, std::unique_ptr should completely own the object it manages, not share that ownership with other classes. std::unique_ptr lives in the <memory> header.

#+begin_src cpp :results output
#include <iostream>
#include <memory>
using namespace std;

class Resource{
public:
    Resource() {cout << "Allocated\n";}
    ~Resource() {cout << "Deallocated\n";}
};

int main() {
    unique_ptr<Resource> res{new Resource()};
    return 0;
}
#+end_src

#+RESULTS:
: Allocated
: Deallocated

std::unique_ptr is based on move semantics so it only owns one object. means it will transfer the ownership

#+begin_src cpp :results output
#include <iostream>
#include <memory>
#include <utility>
using namespace std;

class Resource{
public:
    Resource() {cout << "Allocated\n";}
    ~Resource() {cout << "Deallocated\n";}
};

int main() {
    unique_ptr<Resource> res1{new Resource{}};  // resource allocated
    unique_ptr<Resource> res2{};  // null

    cout << "res1 is " <<  (res1 ? "not null\n" : "null\n");
    cout << "res2 is " <<  (res2 ? "not null\n" : "null\n");

    res2 = move(res1); // here res1 = res2 wont compile because copy assignmant is disabled

    cout << "res1 is " <<  (res1 ? "not null\n" : "null\n");
    cout << "res2 is " <<  (res2 ? "not null\n" : "null\n");

    return 0;
}
#+end_src

#+RESULTS:
: Allocated
: res1 is not null
: res2 is null
: res1 is null
: res2 is not null
: Deallocated

Unlike std::auto_ptr, std::unique_ptr is smart enough to know whether to use scalar delete or array delete, so std::unique_ptr is okay to use with both scalar objects and arrays.

*Passing std::unique_ptr to a function*

#+begin_src cpp :results output
#include <iostream>
#include <memory> // for std::unique_ptr
#include <utility> // for std::move

class Resource
{
public:
	Resource() { std::cout << "Resource acquired\n"; }
	~Resource() { std::cout << "Resource destroyed\n"; }
};

std::ostream& operator<<(std::ostream& out, const Resource&)
{
	out << "I am a resource";
	return out;
}

// This function takes ownership of the Resource, which isn't what we want
void takeOwnership(std::unique_ptr<Resource> res)
{
     if (res)
          std::cout << *res << '\n';
} // the Resource is destroyed here

int main()
{
    auto ptr{ std::make_unique<Resource>() };

//    takeOwnership(ptr); // This doesn't work, need to use move semantics
    takeOwnership(std::move(ptr)); // ok: use move semantics

    std::cout << "Ending program\n";

    return 0;
}
#+end_src

we can pass std::unique to a function like this but it will take ownership which means the object is going to be destroyed at the end of the function. which we dont want.
Instead we pass like this

#+begin_src cpp :results output
#include <memory> // for std::unique_ptr
#include <iostream>

class Resource
{
public:
	Resource() { std::cout << "Resource acquired\n"; }
	~Resource() { std::cout << "Resource destroyed\n"; }
};

std::ostream& operator<<(std::ostream& out, const Resource&)
{
	out << "I am a resource";
	return out;
}

// The function only uses the resource, so we'll accept a pointer to the resource, not a reference to the whole std::unique_ptr<Resource>
void useResource(const Resource* res)
{
	if (res)
		std::cout << *res << '\n';
	else
		std::cout << "No resource\n";
}

int main()
{
	auto ptr{ std::make_unique<Resource>() };

	useResource(ptr.get()); // note: get() used here to get a pointer to the Resource

	std::cout << "Ending program\n";

	return 0;
} // The Resource is destroyed here
#+end_src

#+RESULTS:
: Resource acquired
: I am a resource
: Ending program
: Resource destroyed
